# 1 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
SSAnne_2F_Room5_Frlg_MapScripts::
# 3 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
SSAnne_2F_Room5_EventScript_Gentleman::
# 6 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
# 7 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	end
# 8 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"

# 9 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
SSAnne_2F_Room5_EventScript_LittleBoy::
# 10 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
# 11 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	end
# 12 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"

# 13 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
# 14 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "Have you gone to the SAFARI ZONE\n"
# 15 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "in FUCHSIA CITY?\p"
# 16 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "There are many kinds of rare\n"
# 17 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "POKéMON.$"
# 18 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"

# 19 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
# 20 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "Me and my daddy think the SAFARI\n"
# 21 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "ZONE is awesome!\l"
# 22 "data/maps/SSAnne_2F_Room5_Frlg/scripts.pory"
	.string "I wish we could go there again.$"
