# 1 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Frlg_MapScripts::
# 3 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_RestHouseSign::
# 6 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
# 7 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 8 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 9 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_TrainerTips1::
# 10 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
# 11 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 12 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 13 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_AreaSign::
# 14 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
# 15 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 16 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_TrainerTips2::
# 18 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
# 19 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 20 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 21 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_TrainerTips3::
# 22 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
# 23 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 24 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 25 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_RestHouse::
# 26 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "REST HOUSE$"
# 27 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 28 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_SecretHouseStillAhead::
# 29 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 30 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "The SECRET HOUSE is still ahead.$"
# 31 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 32 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_Area2::
# 33 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "AREA 2$"
# 34 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 35 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_ZigzagThroughTallGrass::
# 36 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 37 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "POKéMON hide in tall grass.\p"
# 38 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "Zigzag through grassy areas to\n"
# 39 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "flush them out.$"
# 40 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 41 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_WinFreeHMFindSecretHouse::
# 42 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 43 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "Win a free HM for finding the\n"
# 44 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "SECRET HOUSE.$"
