# 1 "data/maps/Route2_Frlg/scripts.pory"

# 2 "data/maps/Route2_Frlg/scripts.pory"
Route2_Frlg_MapScripts::
# 3 "data/maps/Route2_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route2_Frlg/scripts.pory"

# 5 "data/maps/Route2_Frlg/scripts.pory"
Route2_EventScript_RouteSign::
# 6 "data/maps/Route2_Frlg/scripts.pory"
	msgbox Route2_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/Route2_Frlg/scripts.pory"
	end
# 8 "data/maps/Route2_Frlg/scripts.pory"

# 9 "data/maps/Route2_Frlg/scripts.pory"
Route2_EventScript_DiglettsCaveSign::
# 10 "data/maps/Route2_Frlg/scripts.pory"
	msgbox Route2_Text_DiglettsCave, MSGBOX_SIGN
# 11 "data/maps/Route2_Frlg/scripts.pory"
	end
# 12 "data/maps/Route2_Frlg/scripts.pory"

# 13 "data/maps/Route2_Frlg/scripts.pory"
Route2_Text_RouteSign::
# 14 "data/maps/Route2_Frlg/scripts.pory"
	.string "ROUTE 2\n"
# 15 "data/maps/Route2_Frlg/scripts.pory"
	.string "VIRIDIAN CITY - PEWTER CITY$"
# 16 "data/maps/Route2_Frlg/scripts.pory"

# 17 "data/maps/Route2_Frlg/scripts.pory"
Route2_Text_DiglettsCave::
# 18 "data/maps/Route2_Frlg/scripts.pory"
	.string "DIGLETT'S CAVE$"
