# 1 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"

# 2 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
SixIsland_WaterPath_House2_Frlg_MapScripts::
# 3 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"

# 5 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
SixIsland_WaterPath_House2_EventScript_Man::
# 6 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	msgbox SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe, MSGBOX_NPC
# 7 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	end
# 8 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"

# 9 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe::
# 10 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	.string "My height is 67.0 inches on the\n"
# 11 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	.string "button.\p"
# 12 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	.string "I know it is this precisely because\n"
# 13 "data/maps/SixIsland_WaterPath_House2_Frlg/scripts.pory"
	.string "my neighbor measured me.$"
