# 1 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 2 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Frlg_MapScripts::
# 3 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 5 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_BrandonIntro::
# 6 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "Do you know anything about this\n"
# 7 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "stone chamber?$"
# 8 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 9 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_BrandonDefeat::
# 10 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "That was uncalled for.\n"
# 11 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "You didn't have to be so rough.$"
# 12 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 13 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_BrandonPostBattle::
# 14 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "The TANOBY RUINS date back at\n"
# 15 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "least 1,500 years.\p"
# 16 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "But it's a baffling mystery as to\n"
# 17 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "why it was built in the first place.$"
# 18 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 19 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_BenjaminIntro::
# 20 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "A mystic POKéMON is said to sleep\n"
# 21 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "inside here.$"
# 22 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 23 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_BenjaminDefeat::
# 24 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "I'm not much good in battle.$"
# 25 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 26 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
# 27 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "I hear there are other ruins like\n"
# 28 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "the one here.\p"
# 29 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "Might they be the resting places\n"
# 30 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "of other mystic POKéMON?$"
# 31 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 32 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_EdnaIntro::
# 33 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "CLIFFORD is teaching me how to\n"
# 34 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "paint.$"
# 35 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 36 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_EdnaDefeat::
# 37 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "We might get in trouble for being\n"
# 38 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "noisy here.$"
# 39 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 40 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_EdnaPostBattle::
# 41 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "I said that I wanted to paint an\n"
# 42 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "old building.\p"
# 43 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "So CLIFFORD brought me here.$"
# 44 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 45 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_CliffordIntro::
# 46 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "Today, in addition to our lesson,\n"
# 47 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "we came to see the chamber.$"
# 48 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 49 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_CliffordDefeat::
# 50 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "My, how extraordinary.$"
# 51 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"

# 52 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
SevenIsland_TanobyRuins_Text_CliffordPostBattle::
# 53 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "Ah, so you are studying POKéMON\n"
# 54 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "on your own…\p"
# 55 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "Yes, you certainly are quite the\n"
# 56 "data/maps/SevenIsland_TanobyRuins_Frlg/scripts.pory"
	.string "extraordinary person, indeed.$"
