# 1 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 2 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Frlg_MapScripts::
# 3 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 5 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_EventScript_Patricia::
# 6 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_PATRICIA, PokemonTower_3F_Text_PatriciaIntro, PokemonTower_3F_Text_PatriciaDefeat
# 7 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	msgbox PokemonTower_3F_Text_PatriciaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	end
# 9 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 10 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_EventScript_Carly::
# 11 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_CARLY, PokemonTower_3F_Text_CarlyIntro, PokemonTower_3F_Text_CarlyDefeat
# 12 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	msgbox PokemonTower_3F_Text_CarlyPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	end
# 14 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 15 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_EventScript_Hope::
# 16 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_HOPE, PokemonTower_3F_Text_HopeIntro, PokemonTower_3F_Text_HopeDefeat
# 17 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	msgbox PokemonTower_3F_Text_HopePostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	end
# 19 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 20 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_HopeIntro::
# 21 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Urrg… Awaa…\n"
# 22 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Huhu… Graa…$"
# 23 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 24 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_HopeDefeat::
# 25 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Hwa!\n"
# 26 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "I'm saved!$"
# 27 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 28 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_HopePostBattle::
# 29 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "The ghosts can be identified by\n"
# 30 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "the SILPH SCOPE.$"
# 31 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 32 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_CarlyIntro::
# 33 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Kekeke…\n"
# 34 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Kwaaah!$"
# 35 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 36 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_CarlyDefeat::
# 37 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Hmm?\n"
# 38 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "What am I doing?$"
# 39 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 40 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_CarlyPostBattle::
# 41 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Sorry!\n"
# 42 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "I was possessed!$"
# 43 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 44 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_PatriciaIntro::
# 45 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Be gone!\n"
# 46 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Malevolent spirit!$"
# 47 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 48 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_PatriciaDefeat::
# 49 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "Whew!\n"
# 50 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "The spirit left!$"
# 51 "data/maps/PokemonTower_3F_Frlg/scripts.pory"

# 52 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
PokemonTower_3F_Text_PatriciaPostBattle::
# 53 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "The others above…\n"
# 54 "data/maps/PokemonTower_3F_Frlg/scripts.pory"
	.string "They must have been possessed.$"
