# 1 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 2 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Frlg_MapScripts::
# 3 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 5 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_EventScript_HornWantedSign::
# 6 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
# 7 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	end
# 8 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 9 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_EventScript_RouteSign::
# 10 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
# 11 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	end
# 12 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 13 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_RoseIntro::
# 14 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I let a pleasant breeze lead me\n"
# 15 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "all the way here.$"
# 16 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 17 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_RoseDefeat::
# 18 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Giggle… You're so cute when you're\n"
# 19 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "determined.$"
# 20 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 21 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_RosePostBattle::
# 22 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I want to go to the woods over\n"
# 23 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "there, but…\p"
# 24 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "There are lots of BUG POKéMON.\n"
# 25 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "They scare me a little.$"
# 26 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 27 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_EdwardIntro::
# 28 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I'm practicing in secret so no one\n"
# 29 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "can see me.$"
# 30 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 31 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_EdwardDefeat::
# 32 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Nobody saw me losing, right?$"
# 33 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 34 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_EdwardPostBattle::
# 35 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "As a performer, I don't want people\n"
# 36 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "to know about the effort I put in.$"
# 37 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 38 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_SamirIntro::
# 39 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "What, you're suggesting that you're\n"
# 40 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "sick of seeing SWIMMERS like me?\p"
# 41 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Aww, don't be hatin'!$"
# 42 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 43 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_SamirDefeat::
# 44 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Oh, no, no, no.$"
# 45 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 46 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_SamirPostBattle::
# 47 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I couldn't lift the stigma of being\n"
# 48 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "a SWIMMER…$"
# 49 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 50 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_DeniseIntro::
# 51 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "My boyfriend's always busy, so I\n"
# 52 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "come swimming by myself.$"
# 53 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 54 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_DeniseDefeat::
# 55 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Awww, I knew this would happen!$"
# 56 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 57 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_DenisePostBattle::
# 58 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "When I can't be with my boyfriend,\n"
# 59 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I spend time with the POKéMON he\l"
# 60 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "gave me.$"
# 61 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 62 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_EarlIntro::
# 63 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Tell me, where are the mountains\n"
# 64 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "around these parts?$"
# 65 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 66 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_EarlDefeat::
# 67 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I lost my way while I was busy\n"
# 68 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "battling!$"
# 69 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 70 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_EarlPostBattle::
# 71 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Aren't there any mountains around\n"
# 72 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "these parts?$"
# 73 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 74 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiuIntro::
# 75 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIU: Hello, POKéMON!\n"
# 76 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "It's time to play!$"
# 77 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 78 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiuDefeat::
# 79 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIU: Oh, no!\n"
# 80 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Mommy!$"
# 81 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 82 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiuPostBattle::
# 83 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIU: It makes me all sad inside\n"
# 84 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "when we lose…$"
# 85 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 86 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiuNotEnoughMons::
# 87 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIU: MIA and I are TWINS.\n"
# 88 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "We want to battle together.$"
# 89 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 90 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiaIntro::
# 91 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIA: Hello, POKéMON!\n"
# 92 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "It's time to battle!$"
# 93 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 94 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiaDefeat::
# 95 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIA: You're mean!\n"
# 96 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "You're bad for winning!$"
# 97 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 98 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiaPostBattle::
# 99 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIA: Ohh…\n"
# 100 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "I'm sorry, my POKéMON…$"
# 101 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 102 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_MiaNotEnoughMons::
# 103 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "MIA: Oh, you only have one\n"
# 104 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "POKéMON?\p"
# 105 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Don't you feel lonesome?$"
# 106 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 107 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_WantedUltimateHorn::
# 108 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Wanted!\n"
# 109 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "The Ultimate Horn!$"
# 110 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"

# 111 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
SixIsland_WaterPath_Text_RouteSign::
# 112 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "WATER PATH\n"
# 113 "data/maps/SixIsland_WaterPath_Frlg/scripts.pory"
	.string "Leads to RUIN VALLEY$"
