# 1 "data/maps/Route9_Frlg/scripts.pory"

# 2 "data/maps/Route9_Frlg/scripts.pory"
Route9_Frlg_MapScripts::
# 3 "data/maps/Route9_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route9_Frlg/scripts.pory"

# 5 "data/maps/Route9_Frlg/scripts.pory"
Route9_EventScript_RouteSign::
# 6 "data/maps/Route9_Frlg/scripts.pory"
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/Route9_Frlg/scripts.pory"
	end
# 8 "data/maps/Route9_Frlg/scripts.pory"

# 9 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_AliciaIntro::
# 10 "data/maps/Route9_Frlg/scripts.pory"
	.string "You have POKéMON with you!\n"
# 11 "data/maps/Route9_Frlg/scripts.pory"
	.string "You're mine!$"
# 12 "data/maps/Route9_Frlg/scripts.pory"

# 13 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_AliciaDefeat::
# 14 "data/maps/Route9_Frlg/scripts.pory"
	.string "You deceived me…$"
# 15 "data/maps/Route9_Frlg/scripts.pory"

# 16 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_AliciaPostBattle::
# 17 "data/maps/Route9_Frlg/scripts.pory"
	.string "The tunnel coming up is pitch-black\n"
# 18 "data/maps/Route9_Frlg/scripts.pory"
	.string "inside.\p"
# 19 "data/maps/Route9_Frlg/scripts.pory"
	.string "You'll need FLASH to get through\n"
# 20 "data/maps/Route9_Frlg/scripts.pory"
	.string "there.$"
# 21 "data/maps/Route9_Frlg/scripts.pory"

# 22 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_ChrisIntro::
# 23 "data/maps/Route9_Frlg/scripts.pory"
	.string "Who's that walking there with those\n"
# 24 "data/maps/Route9_Frlg/scripts.pory"
	.string "good-looking POKéMON?$"
# 25 "data/maps/Route9_Frlg/scripts.pory"

# 26 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_ChrisDefeat::
# 27 "data/maps/Route9_Frlg/scripts.pory"
	.string "Out like a light!$"
# 28 "data/maps/Route9_Frlg/scripts.pory"

# 29 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_ChrisPostBattle::
# 30 "data/maps/Route9_Frlg/scripts.pory"
	.string "Keep walking!$"
# 31 "data/maps/Route9_Frlg/scripts.pory"

# 32 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_DrewIntro::
# 33 "data/maps/Route9_Frlg/scripts.pory"
	.string "I'm taking the ROCK TUNNEL to\n"
# 34 "data/maps/Route9_Frlg/scripts.pory"
	.string "go to LAVENDER…$"
# 35 "data/maps/Route9_Frlg/scripts.pory"

# 36 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_DrewDefeat::
# 37 "data/maps/Route9_Frlg/scripts.pory"
	.string "Can't measure up…$"
# 38 "data/maps/Route9_Frlg/scripts.pory"

# 39 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_DrewPostBattle::
# 40 "data/maps/Route9_Frlg/scripts.pory"
	.string "Are you off to ROCK TUNNEL, too?$"
# 41 "data/maps/Route9_Frlg/scripts.pory"

# 42 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_CaitlinIntro::
# 43 "data/maps/Route9_Frlg/scripts.pory"
	.string "Don't you dare patronize me!$"
# 44 "data/maps/Route9_Frlg/scripts.pory"

# 45 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_CaitlinDefeat::
# 46 "data/maps/Route9_Frlg/scripts.pory"
	.string "No!\n"
# 47 "data/maps/Route9_Frlg/scripts.pory"
	.string "You're too much.$"
# 48 "data/maps/Route9_Frlg/scripts.pory"

# 49 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_CaitlinPostBattle::
# 50 "data/maps/Route9_Frlg/scripts.pory"
	.string "You're obviously talented.\n"
# 51 "data/maps/Route9_Frlg/scripts.pory"
	.string "Good luck to you!$"
# 52 "data/maps/Route9_Frlg/scripts.pory"

# 53 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_JeremyIntro::
# 54 "data/maps/Route9_Frlg/scripts.pory"
	.string "Bwahaha!\n"
# 55 "data/maps/Route9_Frlg/scripts.pory"
	.string "Great! I was bored, eh!$"
# 56 "data/maps/Route9_Frlg/scripts.pory"

# 57 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_JeremyDefeat::
# 58 "data/maps/Route9_Frlg/scripts.pory"
	.string "Keep it coming, eh!\p"
# 59 "data/maps/Route9_Frlg/scripts.pory"
	.string "Oh wait.\n"
# 60 "data/maps/Route9_Frlg/scripts.pory"
	.string "I'm out of POKéMON!$"
# 61 "data/maps/Route9_Frlg/scripts.pory"

# 62 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_JeremyPostBattle::
# 63 "data/maps/Route9_Frlg/scripts.pory"
	.string "You sure had guts standing up to\n"
# 64 "data/maps/Route9_Frlg/scripts.pory"
	.string "me there, eh?$"
# 65 "data/maps/Route9_Frlg/scripts.pory"

# 66 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_BriceIntro::
# 67 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahaha!\n"
# 68 "data/maps/Route9_Frlg/scripts.pory"
	.string "Aren't you a little toughie!$"
# 69 "data/maps/Route9_Frlg/scripts.pory"

# 70 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_BriceDefeat::
# 71 "data/maps/Route9_Frlg/scripts.pory"
	.string "What's that?$"
# 72 "data/maps/Route9_Frlg/scripts.pory"

# 73 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_BricePostBattle::
# 74 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahaha!\n"
# 75 "data/maps/Route9_Frlg/scripts.pory"
	.string "Kids should be tough!$"
# 76 "data/maps/Route9_Frlg/scripts.pory"

# 77 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_BrentIntro::
# 78 "data/maps/Route9_Frlg/scripts.pory"
	.string "I got up early every day to raise\n"
# 79 "data/maps/Route9_Frlg/scripts.pory"
	.string "my POKéMON from cocoons!$"
# 80 "data/maps/Route9_Frlg/scripts.pory"

# 81 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_BrentDefeat::
# 82 "data/maps/Route9_Frlg/scripts.pory"
	.string "WHAT?\p"
# 83 "data/maps/Route9_Frlg/scripts.pory"
	.string "What a total waste of time!$"
# 84 "data/maps/Route9_Frlg/scripts.pory"

# 85 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_BrentPostBattle::
# 86 "data/maps/Route9_Frlg/scripts.pory"
	.string "I have to collect more than bugs\n"
# 87 "data/maps/Route9_Frlg/scripts.pory"
	.string "to get stronger…$"
# 88 "data/maps/Route9_Frlg/scripts.pory"

# 89 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_AlanIntro::
# 90 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahahaha!\n"
# 91 "data/maps/Route9_Frlg/scripts.pory"
	.string "Bring it on!$"
# 92 "data/maps/Route9_Frlg/scripts.pory"

# 93 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_AlanDefeat::
# 94 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahahaha!\n"
# 95 "data/maps/Route9_Frlg/scripts.pory"
	.string "You beat me fair!$"
# 96 "data/maps/Route9_Frlg/scripts.pory"

# 97 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_AlanPostBattle::
# 98 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahahaha!\n"
# 99 "data/maps/Route9_Frlg/scripts.pory"
	.string "Us hearty guys always laugh!$"
# 100 "data/maps/Route9_Frlg/scripts.pory"

# 101 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_ConnerIntro::
# 102 "data/maps/Route9_Frlg/scripts.pory"
	.string "Go, my super BUG POKéMON!$"
# 103 "data/maps/Route9_Frlg/scripts.pory"

# 104 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_ConnerDefeat::
# 105 "data/maps/Route9_Frlg/scripts.pory"
	.string "My bugs…$"
# 106 "data/maps/Route9_Frlg/scripts.pory"

# 107 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_ConnerPostBattle::
# 108 "data/maps/Route9_Frlg/scripts.pory"
	.string "If you don't like BUG POKéMON,\n"
# 109 "data/maps/Route9_Frlg/scripts.pory"
	.string "you bug me!$"
# 110 "data/maps/Route9_Frlg/scripts.pory"

# 111 "data/maps/Route9_Frlg/scripts.pory"
Route9_Text_RouteSign::
# 112 "data/maps/Route9_Frlg/scripts.pory"
	.string "ROUTE 9\n"
# 113 "data/maps/Route9_Frlg/scripts.pory"
	.string "CERULEAN CITY - ROCK TUNNEL$"
