# 1 "data/maps/Route21_South_Frlg/scripts.pory"

# 2 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Frlg_MapScripts::
# 3 "data/maps/Route21_South_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route21_South_Frlg/scripts.pory"

# 5 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_JackIntro::
# 6 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "I caught my POKéMON at sea.$"
# 7 "data/maps/Route21_South_Frlg/scripts.pory"

# 8 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_JackDefeat::
# 9 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Diver!!\n"
# 10 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Down!!$"
# 11 "data/maps/Route21_South_Frlg/scripts.pory"

# 12 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_JackPostBattle::
# 13 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Where'd you catch your POKéMON?$"
# 14 "data/maps/Route21_South_Frlg/scripts.pory"

# 15 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_JeromeIntro::
# 16 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Right now, I'm in a triathlon meet.$"
# 17 "data/maps/Route21_South_Frlg/scripts.pory"

# 18 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_JeromeDefeat::
# 19 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Pant…\n"
# 20 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Pant… Pant…$"
# 21 "data/maps/Route21_South_Frlg/scripts.pory"

# 22 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_JeromePostBattle::
# 23 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "I'm beat! But, I still have the\n"
# 24 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "bike race and marathon left!$"
# 25 "data/maps/Route21_South_Frlg/scripts.pory"

# 26 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_RolandIntro::
# 27 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Ahh!\n"
# 28 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Feel the sun and the wind!$"
# 29 "data/maps/Route21_South_Frlg/scripts.pory"

# 30 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_RolandDefeat::
# 31 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Yow!\n"
# 32 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "I lost!$"
# 33 "data/maps/Route21_South_Frlg/scripts.pory"

# 34 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_RolandPostBattle::
# 35 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "I'm sunburnt to a crisp!$"
# 36 "data/maps/Route21_South_Frlg/scripts.pory"

# 37 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_ClaudeIntro::
# 38 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Hey, don't scare away the fish!$"
# 39 "data/maps/Route21_South_Frlg/scripts.pory"

# 40 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_ClaudeDefeat::
# 41 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Sorry! I'm just so frustrated from\n"
# 42 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "not catching anything.$"
# 43 "data/maps/Route21_South_Frlg/scripts.pory"

# 44 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_ClaudePostBattle::
# 45 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Sheesh, I haven't caught a thing.\n"
# 46 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Could this place actually be a\l"
# 47 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "giant pool or something?$"
# 48 "data/maps/Route21_South_Frlg/scripts.pory"

# 49 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_NolanIntro::
# 50 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Keep me company till I get a hit.$"
# 51 "data/maps/Route21_South_Frlg/scripts.pory"

# 52 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_NolanDefeat::
# 53 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "That burned some time.$"
# 54 "data/maps/Route21_South_Frlg/scripts.pory"

# 55 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_South_Text_NolanPostBattle::
# 56 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Oh wait!\n"
# 57 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "I got a bite! Yeah!$"
# 58 "data/maps/Route21_South_Frlg/scripts.pory"

# 59 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_LilIntro::
# 60 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "LIL: Huh? A battle?\n"
# 61 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "IAN, can't you do it alone?$"
# 62 "data/maps/Route21_South_Frlg/scripts.pory"

# 63 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_LilDefeat::
# 64 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "LIL: Oh, see?\n"
# 65 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "We lost. Happy now?$"
# 66 "data/maps/Route21_South_Frlg/scripts.pory"

# 67 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_LilPostBattle::
# 68 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "LIL: I'm tired.\n"
# 69 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Can't we go home already?$"
# 70 "data/maps/Route21_South_Frlg/scripts.pory"

# 71 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_LilNotEnoughMons::
# 72 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "LIL: Huh? A battle?\n"
# 73 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "I can't be bothered to do it alone.\l"
# 74 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Bring two POKéMON, won't you?$"
# 75 "data/maps/Route21_South_Frlg/scripts.pory"

# 76 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_IanIntro::
# 77 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "IAN: My sis doesn't get enough\n"
# 78 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "exercise, so I made her come.$"
# 79 "data/maps/Route21_South_Frlg/scripts.pory"

# 80 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_IanDefeat::
# 81 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "IAN: Awww, Sis!\n"
# 82 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "Get it together!$"
# 83 "data/maps/Route21_South_Frlg/scripts.pory"

# 84 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_IanPostBattle::
# 85 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "IAN: Come on, Sis!\p"
# 86 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "You're not going to lose weight\n"
# 87 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "like this!$"
# 88 "data/maps/Route21_South_Frlg/scripts.pory"

# 89 "data/maps/Route21_South_Frlg/scripts.pory"
Route21_North_Text_IanNotEnoughMons::
# 90 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "IAN: We want a two-on-two battle.\n"
# 91 "data/maps/Route21_South_Frlg/scripts.pory"
	.string "So can you bring two POKéMON?$"
