# 1 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 2 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_Frlg_MapScripts::
# 3 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 5 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_EventScript_Receptionist::
# 6 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore, MSGBOX_NPC
# 7 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	end
# 8 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 9 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_EventScript_LayoutSign::
# 10 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_1F_Text_FloorDescriptions, MSGBOX_SIGN
# 11 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	end
# 12 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 13 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_EventScript_FloorSign::
# 14 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_1F_Text_ServiceCounter, MSGBOX_SIGN
# 15 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	end
# 16 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 17 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
# 18 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "Hello!\n"
# 19 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "Welcome to CELADON DEPT. STORE.\p"
# 20 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "The board on the right describes\n"
# 21 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "the store layout.$"
# 22 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 23 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
# 24 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "1F: SERVICE COUNTER\p"
# 25 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "2F: TRAINER'S MARKET\p"
# 26 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "3F: TV GAME SHOP\p"
# 27 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "4F: WISE MAN GIFTS\p"
# 28 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "5F: DRUGSTORE\p"
# 29 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "ROOFTOP SQUARE: VENDING MACHINES$"
# 30 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"

# 31 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
# 32 "data/maps/CeladonCity_DepartmentStore_1F_Frlg/scripts.pory"
	.string "1F: SERVICE COUNTER$"
