# 1 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"

# 2 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
Route11_EastEntrance_1F_Frlg_MapScripts::
# 3 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"

# 5 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
Route11_EastEntrance_1F_EventScript_TopGuard::
# 6 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	msgbox Route11_EastEntrance_1F_Text_ManInLavenderRatesNames, MSGBOX_NPC
# 7 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	end
# 8 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"

# 9 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
Route11_EastEntrance_1F_EventScript_BottomGuard::
# 10 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	msgbox Route11_EastEntrance_1F_Text_RockTunnelToReachLavender, MSGBOX_NPC
# 11 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	end
# 12 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"

# 13 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
@ Unclear where this is originally from
# 14 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
Route11_EastEntrance_1F_Text_BagIsFull::
# 15 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "{PLAYER}{KUN}の　バッグ\n"
# 16 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "いっぱい　みたい　だね$"
# 17 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"

# 18 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
# 19 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "Don't you think it's hard to think\n"
# 20 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "up good names for POKéMON?\p"
# 21 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "Especially if you've caught a\n"
# 22 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "whole bunch?\p"
# 23 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "In LAVENDER TOWN, there's a man\n"
# 24 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "who rates POKéMON nicknames.\p"
# 25 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "He can even help you rename your\n"
# 26 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "POKéMON, too.$"
# 27 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"

# 28 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
# 29 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "If you're aiming to reach LAVENDER\n"
# 30 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "TOWN, take ROCK TUNNEL.\p"
# 31 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "You can get to ROCK TUNNEL from\n"
# 32 "data/maps/Route11_EastEntrance_1F_Frlg/scripts.pory"
	.string "CERULEAN CITY.$"
