# 1 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_RestHouse_Frlg_MapScripts::
# 3 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_RestHouse_EventScript_Man::
# 6 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
# 7 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	end
# 8 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 9 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_RestHouse_EventScript_Scientist::
# 10 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
# 11 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	end
# 12 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 13 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_RestHouse_EventScript_CooltrainerF::
# 14 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
# 15 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	end
# 16 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
# 18 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "The SAFARI ZONE's huge, wouldn't\n"
# 19 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "you say?\p"
# 20 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "FUCHSIA's GYM LEADER, KOGA, \n"
# 21 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "patrols the grounds every so often.\p"
# 22 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "Thanks to him, we can play here\n"
# 23 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "knowing that we're safe.$"
# 24 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 25 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
# 26 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "Tossing ROCKS at POKéMON might\n"
# 27 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "make them run, but they'll be\l"
# 28 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "easier to catch.$"
# 29 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 30 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_Text_BaitMakesMonStickAround::
# 31 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "Using BAIT will make POKéMON more\n"
# 32 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "likely to stick around if they get\l"
# 33 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "busy eating.$"
# 34 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"

# 35 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
# 36 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "I hiked a lot, but I didn't see any\n"
# 37 "data/maps/SafariZone_West_RestHouse_Frlg/scripts.pory"
	.string "POKéMON I wanted.$"
