# 1 "data/maps/Route8_Frlg/scripts.pory"

# 2 "data/maps/Route8_Frlg/scripts.pory"
Route8_Frlg_MapScripts::
# 3 "data/maps/Route8_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route8_Frlg/scripts.pory"

# 5 "data/maps/Route8_Frlg/scripts.pory"
Route8_EventScript_UndergroundPathSign::
# 6 "data/maps/Route8_Frlg/scripts.pory"
	msgbox Route8_Text_UndergroundPathSign, MSGBOX_SIGN
# 7 "data/maps/Route8_Frlg/scripts.pory"
	end
# 8 "data/maps/Route8_Frlg/scripts.pory"

# 9 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AidanIntro::
# 10 "data/maps/Route8_Frlg/scripts.pory"
	.string "You look good at POKéMON, but how\n"
# 11 "data/maps/Route8_Frlg/scripts.pory"
	.string "is your chemistry grade?$"
# 12 "data/maps/Route8_Frlg/scripts.pory"

# 13 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AidanDefeat::
# 14 "data/maps/Route8_Frlg/scripts.pory"
	.string "Ow!\n"
# 15 "data/maps/Route8_Frlg/scripts.pory"
	.string "Meltdown!$"
# 16 "data/maps/Route8_Frlg/scripts.pory"

# 17 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AidanPostBattle::
# 18 "data/maps/Route8_Frlg/scripts.pory"
	.string "I am better at school than this!$"
# 19 "data/maps/Route8_Frlg/scripts.pory"

# 20 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_StanIntro::
# 21 "data/maps/Route8_Frlg/scripts.pory"
	.string "All right!\n"
# 22 "data/maps/Route8_Frlg/scripts.pory"
	.string "Let's play a game!$"
# 23 "data/maps/Route8_Frlg/scripts.pory"

# 24 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_StanDefeat::
# 25 "data/maps/Route8_Frlg/scripts.pory"
	.string "Drat!\n"
# 26 "data/maps/Route8_Frlg/scripts.pory"
	.string "Came up short!$"
# 27 "data/maps/Route8_Frlg/scripts.pory"

# 28 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_StanPostBattle::
# 29 "data/maps/Route8_Frlg/scripts.pory"
	.string "Things didn't work today.$"
# 30 "data/maps/Route8_Frlg/scripts.pory"

# 31 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_GlennIntro::
# 32 "data/maps/Route8_Frlg/scripts.pory"
	.string "You should be informed.\n"
# 33 "data/maps/Route8_Frlg/scripts.pory"
	.string "You need strategy to win at this!$"
# 34 "data/maps/Route8_Frlg/scripts.pory"

# 35 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_GlennDefeat::
# 36 "data/maps/Route8_Frlg/scripts.pory"
	.string "It's not logical!$"
# 37 "data/maps/Route8_Frlg/scripts.pory"

# 38 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_GlennPostBattle::
# 39 "data/maps/Route8_Frlg/scripts.pory"
	.string "Go with GRIMER first…and…\n"
# 40 "data/maps/Route8_Frlg/scripts.pory"
	.string "…and…then…$"
# 41 "data/maps/Route8_Frlg/scripts.pory"

# 42 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_PaigeIntro::
# 43 "data/maps/Route8_Frlg/scripts.pory"
	.string "I like NIDORAN, so I collect them!$"
# 44 "data/maps/Route8_Frlg/scripts.pory"

# 45 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_PaigeDefeat::
# 46 "data/maps/Route8_Frlg/scripts.pory"
	.string "Why?\n"
# 47 "data/maps/Route8_Frlg/scripts.pory"
	.string "Why??$"
# 48 "data/maps/Route8_Frlg/scripts.pory"

# 49 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_PaigePostBattle::
# 50 "data/maps/Route8_Frlg/scripts.pory"
	.string "When POKéMON grow up, they get\n"
# 51 "data/maps/Route8_Frlg/scripts.pory"
	.string "ugly! They shouldn't evolve.$"
# 52 "data/maps/Route8_Frlg/scripts.pory"

# 53 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_LeslieIntro::
# 54 "data/maps/Route8_Frlg/scripts.pory"
	.string "School is fun, but so are POKéMON.$"
# 55 "data/maps/Route8_Frlg/scripts.pory"

# 56 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_LeslieDefeat::
# 57 "data/maps/Route8_Frlg/scripts.pory"
	.string "You made it clear to me that\n"
# 58 "data/maps/Route8_Frlg/scripts.pory"
	.string "I should stick with school.$"
# 59 "data/maps/Route8_Frlg/scripts.pory"

# 60 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_LesliePostBattle::
# 61 "data/maps/Route8_Frlg/scripts.pory"
	.string "I was planning on getting some\n"
# 62 "data/maps/Route8_Frlg/scripts.pory"
	.string "fresh air for a change, but…\p"
# 63 "data/maps/Route8_Frlg/scripts.pory"
	.string "We're stuck here because of the\n"
# 64 "data/maps/Route8_Frlg/scripts.pory"
	.string "gates at SAFFRON.$"
# 65 "data/maps/Route8_Frlg/scripts.pory"

# 66 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AndreaIntro::
# 67 "data/maps/Route8_Frlg/scripts.pory"
	.string "MEOWTH is so cute, meow, meow,\n"
# 68 "data/maps/Route8_Frlg/scripts.pory"
	.string "meow!$"
# 69 "data/maps/Route8_Frlg/scripts.pory"

# 70 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AndreaDefeat::
# 71 "data/maps/Route8_Frlg/scripts.pory"
	.string "Meeeeyow!$"
# 72 "data/maps/Route8_Frlg/scripts.pory"

# 73 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AndreaPostBattle::
# 74 "data/maps/Route8_Frlg/scripts.pory"
	.string "I think PIDGEY and RATTATA are\n"
# 75 "data/maps/Route8_Frlg/scripts.pory"
	.string "cute, too!$"
# 76 "data/maps/Route8_Frlg/scripts.pory"

# 77 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_MeganIntro::
# 78 "data/maps/Route8_Frlg/scripts.pory"
	.string "We must look silly standing here\n"
# 79 "data/maps/Route8_Frlg/scripts.pory"
	.string "like this.$"
# 80 "data/maps/Route8_Frlg/scripts.pory"

# 81 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_MeganDefeat::
# 82 "data/maps/Route8_Frlg/scripts.pory"
	.string "Look what you did to my poor, cute\n"
# 83 "data/maps/Route8_Frlg/scripts.pory"
	.string "POKéMON!$"
# 84 "data/maps/Route8_Frlg/scripts.pory"

# 85 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_MeganPostBattle::
# 86 "data/maps/Route8_Frlg/scripts.pory"
	.string "SAFFRON's gatekeeper won't let us\n"
# 87 "data/maps/Route8_Frlg/scripts.pory"
	.string "go through.\p"
# 88 "data/maps/Route8_Frlg/scripts.pory"
	.string "I know he's doing his job, but I\n"
# 89 "data/maps/Route8_Frlg/scripts.pory"
	.string "think he's mean.$"
# 90 "data/maps/Route8_Frlg/scripts.pory"

# 91 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_RichIntro::
# 92 "data/maps/Route8_Frlg/scripts.pory"
	.string "I'm a rambling, gaming dude!$"
# 93 "data/maps/Route8_Frlg/scripts.pory"

# 94 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_RichDefeat::
# 95 "data/maps/Route8_Frlg/scripts.pory"
	.string "Missed the big chance!$"
# 96 "data/maps/Route8_Frlg/scripts.pory"

# 97 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_RichPostBattle::
# 98 "data/maps/Route8_Frlg/scripts.pory"
	.string "Playing games and POKéMON are like\n"
# 99 "data/maps/Route8_Frlg/scripts.pory"
	.string "eating peanuts! I just can't stop!$"
# 100 "data/maps/Route8_Frlg/scripts.pory"

# 101 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_JuliaIntro::
# 102 "data/maps/Route8_Frlg/scripts.pory"
	.string "What's a cute, round, and fluffy\n"
# 103 "data/maps/Route8_Frlg/scripts.pory"
	.string "POKéMON?$"
# 104 "data/maps/Route8_Frlg/scripts.pory"

# 105 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_JuliaDefeat::
# 106 "data/maps/Route8_Frlg/scripts.pory"
	.string "Stop!\p"
# 107 "data/maps/Route8_Frlg/scripts.pory"
	.string "Don't be so mean to my CLEFAIRY!$"
# 108 "data/maps/Route8_Frlg/scripts.pory"

# 109 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_JuliaPostBattle::
# 110 "data/maps/Route8_Frlg/scripts.pory"
	.string "I read that CLEFAIRY evolves when\n"
# 111 "data/maps/Route8_Frlg/scripts.pory"
	.string "it's exposed to a MOON STONE.\p"
# 112 "data/maps/Route8_Frlg/scripts.pory"
	.string "I read that in a POKéMON JOURNAL.\n"
# 113 "data/maps/Route8_Frlg/scripts.pory"
	.string "I wonder if it's true?$"
# 114 "data/maps/Route8_Frlg/scripts.pory"

# 115 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_UndergroundPathSign::
# 116 "data/maps/Route8_Frlg/scripts.pory"
	.string "UNDERGROUND PATH\n"
# 117 "data/maps/Route8_Frlg/scripts.pory"
	.string "CELADON CITY - LAVENDER TOWN$"
# 118 "data/maps/Route8_Frlg/scripts.pory"

# 119 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_EliIntro::
# 120 "data/maps/Route8_Frlg/scripts.pory"
	.string "ELI: Twin power is fantastic.\n"
# 121 "data/maps/Route8_Frlg/scripts.pory"
	.string "Did you know?$"
# 122 "data/maps/Route8_Frlg/scripts.pory"

# 123 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_EliDefeat::
# 124 "data/maps/Route8_Frlg/scripts.pory"
	.string "ELI: But…\n"
# 125 "data/maps/Route8_Frlg/scripts.pory"
	.string "We used our twin power…$"
# 126 "data/maps/Route8_Frlg/scripts.pory"

# 127 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_EliPostBattle::
# 128 "data/maps/Route8_Frlg/scripts.pory"
	.string "ELI: I caught my POKéMON with\n"
# 129 "data/maps/Route8_Frlg/scripts.pory"
	.string "ANNE!$"
# 130 "data/maps/Route8_Frlg/scripts.pory"

# 131 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_EliNotEnoughMons::
# 132 "data/maps/Route8_Frlg/scripts.pory"
	.string "ELI: We can't battle if you don't\n"
# 133 "data/maps/Route8_Frlg/scripts.pory"
	.string "have two POKéMON.$"
# 134 "data/maps/Route8_Frlg/scripts.pory"

# 135 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AnneIntro::
# 136 "data/maps/Route8_Frlg/scripts.pory"
	.string "ANNE: We'll shock you with our twin\n"
# 137 "data/maps/Route8_Frlg/scripts.pory"
	.string "power!$"
# 138 "data/maps/Route8_Frlg/scripts.pory"

# 139 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AnneDefeat::
# 140 "data/maps/Route8_Frlg/scripts.pory"
	.string "ANNE: Our twin power…$"
# 141 "data/maps/Route8_Frlg/scripts.pory"

# 142 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AnnePostBattle::
# 143 "data/maps/Route8_Frlg/scripts.pory"
	.string "ANNE: I'm raising POKéMON with\n"
# 144 "data/maps/Route8_Frlg/scripts.pory"
	.string "ELI.$"
# 145 "data/maps/Route8_Frlg/scripts.pory"

# 146 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_AnneNotEnoughMons::
# 147 "data/maps/Route8_Frlg/scripts.pory"
	.string "ANNE: Hi, hi! Let's battle!\n"
# 148 "data/maps/Route8_Frlg/scripts.pory"
	.string "But bring two POKéMON.$"
# 149 "data/maps/Route8_Frlg/scripts.pory"

# 150 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_RicardoIntro::
# 151 "data/maps/Route8_Frlg/scripts.pory"
	.string "My bike's acting up, man.$"
# 152 "data/maps/Route8_Frlg/scripts.pory"

# 153 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_RicardoDefeat::
# 154 "data/maps/Route8_Frlg/scripts.pory"
	.string "Aww, man.\n"
# 155 "data/maps/Route8_Frlg/scripts.pory"
	.string "I'm not into this.$"
# 156 "data/maps/Route8_Frlg/scripts.pory"

# 157 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_RicardoPostBattle::
# 158 "data/maps/Route8_Frlg/scripts.pory"
	.string "I got grass caught up in my\n"
# 159 "data/maps/Route8_Frlg/scripts.pory"
	.string "spokes, man.$"
# 160 "data/maps/Route8_Frlg/scripts.pory"

# 161 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_JarenIntro::
# 162 "data/maps/Route8_Frlg/scripts.pory"
	.string "Clear the way, or I'll run you\n"
# 163 "data/maps/Route8_Frlg/scripts.pory"
	.string "down!$"
# 164 "data/maps/Route8_Frlg/scripts.pory"

# 165 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_JarenDefeat::
# 166 "data/maps/Route8_Frlg/scripts.pory"
	.string "You for real, kid?$"
# 167 "data/maps/Route8_Frlg/scripts.pory"

# 168 "data/maps/Route8_Frlg/scripts.pory"
Route8_Text_JarenPostBattle::
# 169 "data/maps/Route8_Frlg/scripts.pory"
	.string "Don't think you're all special and\n"
# 170 "data/maps/Route8_Frlg/scripts.pory"
	.string "all just because of this.$"
