# 1 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 2 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Frlg_MapScripts::
# 3 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 5 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_EventScript_RouteSign::
# 6 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	msgbox SevenIsland_SevaultCanyon_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	end
# 8 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 9 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_CyndyIntro::
# 10 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "My conditioning's in top form!$"
# 11 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 12 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_CyndyDefeat::
# 13 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Huh?\n"
# 14 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Something's not right…$"
# 15 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 16 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
# 17 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "The way I am now, I may have to\n"
# 18 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "hold off on TRAINER TOWER…$"
# 19 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 20 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_EvanIntro::
# 21 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "It doesn't matter if you happen to\n"
# 22 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "have the strongest POKéMON…\p"
# 23 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "It doesn't mean a thing if you don't\n"
# 24 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "know how to use them properly!$"
# 25 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 26 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_EvanDefeat::
# 27 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "You're a master at this.$"
# 28 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 29 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_EvanPostBattle::
# 30 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "You see them every so often,\n"
# 31 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "TRAINERS with awesome POKéMON\l"
# 32 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "who have no idea what to do.\p"
# 33 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Before training POKéMON, TRAINERS\n"
# 34 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "themselves need to grow up.$"
# 35 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 36 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_JacksonIntro::
# 37 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "I work to protect the environment.\n"
# 38 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "In turn, nature protects me!$"
# 39 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 40 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_JacksonDefeat::
# 41 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Whoa! You're tough!\n"
# 42 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "How about protecting me?$"
# 43 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 44 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
# 45 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "From far out among the stars, our\n"
# 46 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "planet is just a drop of water.\p"
# 47 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "But we want to protect that drop\n"
# 48 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "of water for everyone.$"
# 49 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 50 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_KatelynIntro::
# 51 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Those shoes you have are pretty\n"
# 52 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "snazzy.$"
# 53 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 54 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_KatelynDefeat::
# 55 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "You're hot stuff in spite of your\n"
# 56 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "cute looks.$"
# 57 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 58 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
# 59 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Your mom bought those snazzy\n"
# 60 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "RUNNING SHOES for you?\p"
# 61 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "She must adore you.$"
# 62 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 63 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LeroyIntro::
# 64 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "You look strong.\n"
# 65 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Let me battle you, please!$"
# 66 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 67 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LeroyDefeat::
# 68 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "I knew it!\n"
# 69 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "You're as tough as I thought!$"
# 70 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 71 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
# 72 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "The way you battle has given me\n"
# 73 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "a lot of useful data.\p"
# 74 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Thanks so much!$"
# 75 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 76 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_MichelleIntro::
# 77 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "I was given the best possible\n"
# 78 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "education to become this strong.\p"
# 79 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "I don't want to lose to anyone!$"
# 80 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 81 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_MichelleDefeat::
# 82 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Thank you. I feel like I've been\n"
# 83 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "set free by losing to you.$"
# 84 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 85 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_MichellePostBattle::
# 86 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "For some reason, I get furious\n"
# 87 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "over the slightest thing.\p"
# 88 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "I'll calm myself by breathing\n"
# 89 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "deeply.$"
# 90 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 91 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LexIntro::
# 92 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "LEX: My darling NYA, together\n"
# 93 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "we could win!$"
# 94 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 95 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LexDefeat::
# 96 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "LEX: I seem to have been too\n"
# 97 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "careless…$"
# 98 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 99 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LexPostBattle::
# 100 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "LEX: I think it was a good\n"
# 101 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "experience for NYA.\p"
# 102 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "You have my gratitude.$"
# 103 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 104 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
# 105 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "LEX: May I ask you to battle the\n"
# 106 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "both of us at the same time?$"
# 107 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 108 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_NyaIntro::
# 109 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "NYA: I'll do my best so I won't\n"
# 110 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "drag down my mentor, LEX!$"
# 111 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 112 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_NyaDefeat::
# 113 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "NYA: Oh, no…\n"
# 114 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "I'm so sorry, I…$"
# 115 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 116 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_NyaPostBattle::
# 117 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "NYA: I think I'm going to need\n"
# 118 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "much more seasoning and tutoring\l"
# 119 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "under LEX…\p"
# 120 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "…So, LEX, please, may I stay with\n"
# 121 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "you like this?$"
# 122 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 123 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
# 124 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "NYA: I'm sorry, but may we battle\n"
# 125 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "in two-on-two style?$"
# 126 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 127 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_RouteSign::
# 128 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "SEVAULT CANYON\n"
# 129 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "TANOBY RUINS AHEAD$"
# 130 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"

# 131 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
# 132 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Training by oneself is certainly\n"
# 133 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "not a bad thing.\p"
# 134 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "But it's also not bad to aim for\n"
# 135 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "the top with a partner.\p"
# 136 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "Even BRUNO…\n"
# 137 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "He trained with a fellow by the\l"
# 138 "data/maps/SevenIsland_SevaultCanyon_Frlg/scripts.pory"
	.string "name of BRAWLY before.$"
