# 1 "data/maps/Route11_Frlg/scripts.pory"

# 2 "data/maps/Route11_Frlg/scripts.pory"
Route11_Frlg_MapScripts::
# 3 "data/maps/Route11_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route11_Frlg/scripts.pory"

# 5 "data/maps/Route11_Frlg/scripts.pory"
Route11_EventScript_DiglettsCaveSign::
# 6 "data/maps/Route11_Frlg/scripts.pory"
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
# 7 "data/maps/Route11_Frlg/scripts.pory"
	end
# 8 "data/maps/Route11_Frlg/scripts.pory"

# 9 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_HugoIntro::
# 10 "data/maps/Route11_Frlg/scripts.pory"
	.string "Win, lose, or draw!$"
# 11 "data/maps/Route11_Frlg/scripts.pory"

# 12 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_HugoDefeat::
# 13 "data/maps/Route11_Frlg/scripts.pory"
	.string "Atcha!\n"
# 14 "data/maps/Route11_Frlg/scripts.pory"
	.string "Didn't go my way!$"
# 15 "data/maps/Route11_Frlg/scripts.pory"

# 16 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_HugoPostBattle::
# 17 "data/maps/Route11_Frlg/scripts.pory"
	.string "POKéMON is life!\n"
# 18 "data/maps/Route11_Frlg/scripts.pory"
	.string "And to live is to play games!$"
# 19 "data/maps/Route11_Frlg/scripts.pory"

# 20 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_JasperIntro::
# 21 "data/maps/Route11_Frlg/scripts.pory"
	.string "Competition!\n"
# 22 "data/maps/Route11_Frlg/scripts.pory"
	.string "I can't get enough!$"
# 23 "data/maps/Route11_Frlg/scripts.pory"

# 24 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_JasperDefeat::
# 25 "data/maps/Route11_Frlg/scripts.pory"
	.string "I had a chance!$"
# 26 "data/maps/Route11_Frlg/scripts.pory"

# 27 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_JasperPostBattle::
# 28 "data/maps/Route11_Frlg/scripts.pory"
	.string "You can't be a coward in the world\n"
# 29 "data/maps/Route11_Frlg/scripts.pory"
	.string "of POKéMON!$"
# 30 "data/maps/Route11_Frlg/scripts.pory"

# 31 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_EddieIntro::
# 32 "data/maps/Route11_Frlg/scripts.pory"
	.string "Let's go, but don't cheat!$"
# 33 "data/maps/Route11_Frlg/scripts.pory"

# 34 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_EddieDefeat::
# 35 "data/maps/Route11_Frlg/scripts.pory"
	.string "Huh?\n"
# 36 "data/maps/Route11_Frlg/scripts.pory"
	.string "That's not right!$"
# 37 "data/maps/Route11_Frlg/scripts.pory"

# 38 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_EddiePostBattle::
# 39 "data/maps/Route11_Frlg/scripts.pory"
	.string "I did my best.\n"
# 40 "data/maps/Route11_Frlg/scripts.pory"
	.string "I have no regrets.$"
# 41 "data/maps/Route11_Frlg/scripts.pory"

# 42 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_BraxtonIntro::
# 43 "data/maps/Route11_Frlg/scripts.pory"
	.string "Careful!\n"
# 44 "data/maps/Route11_Frlg/scripts.pory"
	.string "I'm laying down some cables!$"
# 45 "data/maps/Route11_Frlg/scripts.pory"

# 46 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_BraxtonDefeat::
# 47 "data/maps/Route11_Frlg/scripts.pory"
	.string "That was electric!$"
# 48 "data/maps/Route11_Frlg/scripts.pory"

# 49 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_BraxtonPostBattle::
# 50 "data/maps/Route11_Frlg/scripts.pory"
	.string "Spread the word to save energy!$"
# 51 "data/maps/Route11_Frlg/scripts.pory"

# 52 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DillonIntro::
# 53 "data/maps/Route11_Frlg/scripts.pory"
	.string "I just became a TRAINER.\n"
# 54 "data/maps/Route11_Frlg/scripts.pory"
	.string "But, I think I can win.$"
# 55 "data/maps/Route11_Frlg/scripts.pory"

# 56 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DillonDefeat::
# 57 "data/maps/Route11_Frlg/scripts.pory"
	.string "My POKéMON couldn't win…\n"
# 58 "data/maps/Route11_Frlg/scripts.pory"
	.string "Haven't they grown enough?$"
# 59 "data/maps/Route11_Frlg/scripts.pory"

# 60 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DillonPostBattle::
# 61 "data/maps/Route11_Frlg/scripts.pory"
	.string "What now?\n"
# 62 "data/maps/Route11_Frlg/scripts.pory"
	.string "Leave me alone!$"
# 63 "data/maps/Route11_Frlg/scripts.pory"

# 64 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DirkIntro::
# 65 "data/maps/Route11_Frlg/scripts.pory"
	.string "Fwahaha!\n"
# 66 "data/maps/Route11_Frlg/scripts.pory"
	.string "I have never lost!$"
# 67 "data/maps/Route11_Frlg/scripts.pory"

# 68 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DirkDefeat::
# 69 "data/maps/Route11_Frlg/scripts.pory"
	.string "My first loss!$"
# 70 "data/maps/Route11_Frlg/scripts.pory"

# 71 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DirkPostBattle::
# 72 "data/maps/Route11_Frlg/scripts.pory"
	.string "You were just lucky, that's all.$"
# 73 "data/maps/Route11_Frlg/scripts.pory"

# 74 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DarianIntro::
# 75 "data/maps/Route11_Frlg/scripts.pory"
	.string "I have never won before…$"
# 76 "data/maps/Route11_Frlg/scripts.pory"

# 77 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DarianDefeat::
# 78 "data/maps/Route11_Frlg/scripts.pory"
	.string "I saw this coming…$"
# 79 "data/maps/Route11_Frlg/scripts.pory"

# 80 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DarianPostBattle::
# 81 "data/maps/Route11_Frlg/scripts.pory"
	.string "I was unlucky, as always.$"
# 82 "data/maps/Route11_Frlg/scripts.pory"

# 83 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_YasuIntro::
# 84 "data/maps/Route11_Frlg/scripts.pory"
	.string "I'm the best in my class.\n"
# 85 "data/maps/Route11_Frlg/scripts.pory"
	.string "I train every morning.$"
# 86 "data/maps/Route11_Frlg/scripts.pory"

# 87 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_YasuDefeat::
# 88 "data/maps/Route11_Frlg/scripts.pory"
	.string "Darn!\n"
# 89 "data/maps/Route11_Frlg/scripts.pory"
	.string "My POKéMON need to be stronger!$"
# 90 "data/maps/Route11_Frlg/scripts.pory"

# 91 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_YasuPostBattle::
# 92 "data/maps/Route11_Frlg/scripts.pory"
	.string "There's a fat POKéMON that comes\n"
# 93 "data/maps/Route11_Frlg/scripts.pory"
	.string "down from the mountains.\p"
# 94 "data/maps/Route11_Frlg/scripts.pory"
	.string "I bet it'd be strong if you can\n"
# 95 "data/maps/Route11_Frlg/scripts.pory"
	.string "catch it.$"
# 96 "data/maps/Route11_Frlg/scripts.pory"

# 97 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_BernieIntro::
# 98 "data/maps/Route11_Frlg/scripts.pory"
	.string "Watch out for live wires!$"
# 99 "data/maps/Route11_Frlg/scripts.pory"

# 100 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_BernieDefeat::
# 101 "data/maps/Route11_Frlg/scripts.pory"
	.string "Whoa!\n"
# 102 "data/maps/Route11_Frlg/scripts.pory"
	.string "You spark plug!$"
# 103 "data/maps/Route11_Frlg/scripts.pory"

# 104 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_BerniePostBattle::
# 105 "data/maps/Route11_Frlg/scripts.pory"
	.string "Well, better get back to work.$"
# 106 "data/maps/Route11_Frlg/scripts.pory"

# 107 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DaveIntro::
# 108 "data/maps/Route11_Frlg/scripts.pory"
	.string "I raised my POKéMON carefully.\n"
# 109 "data/maps/Route11_Frlg/scripts.pory"
	.string "They should be ready by now!$"
# 110 "data/maps/Route11_Frlg/scripts.pory"

# 111 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DaveDefeat::
# 112 "data/maps/Route11_Frlg/scripts.pory"
	.string "Bye-bye!\n"
# 113 "data/maps/Route11_Frlg/scripts.pory"
	.string "Thank you, and good-bye!$"
# 114 "data/maps/Route11_Frlg/scripts.pory"

# 115 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DavePostBattle::
# 116 "data/maps/Route11_Frlg/scripts.pory"
	.string "Tch…\n"
# 117 "data/maps/Route11_Frlg/scripts.pory"
	.string "I better go find stronger ones!$"
# 118 "data/maps/Route11_Frlg/scripts.pory"

# 119 "data/maps/Route11_Frlg/scripts.pory"
Route11_Text_DiglettsCave::
# 120 "data/maps/Route11_Frlg/scripts.pory"
	.string "DIGLETT'S CAVE$"
