# 1 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 2 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Frlg_MapScripts::
# 3 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 5 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Sofia::
# 6 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaIntro, RockTunnel_B1F_Text_SofiaDefeat
# 7 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_SofiaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 9 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 10 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Martha::
# 11 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaIntro, RockTunnel_B1F_Text_MarthaDefeat
# 12 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_MarthaPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 14 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 15 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Dudley::
# 16 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleyIntro, RockTunnel_B1F_Text_DudleyDefeat
# 17 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_DudleyPostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 19 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 20 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Allen::
# 21 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ALLEN, RockTunnel_B1F_Text_AllenIntro, RockTunnel_B1F_Text_AllenDefeat
# 22 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 24 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 25 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Eric::
# 26 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ERIC, RockTunnel_B1F_Text_EricIntro, RockTunnel_B1F_Text_EricDefeat
# 27 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_EricPostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 29 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 30 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Cooper::
# 31 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperIntro, RockTunnel_B1F_Text_CooperDefeat
# 32 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_CooperPostBattle, MSGBOX_AUTOCLOSE
# 33 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 34 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 35 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Steve::
# 36 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveIntro, RockTunnel_B1F_Text_SteveDefeat
# 37 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_StevePostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 39 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 40 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Winston::
# 41 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonIntro, RockTunnel_B1F_Text_WinstonDefeat
# 42 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_WinstonPostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 44 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 45 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SofiaIntro::
# 46 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Do you know how you can avoid\n"
# 47 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "getting lost in the mountains?\p"
# 48 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "You can bend twigs as trail\n"
# 49 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "markers.$"
# 50 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 51 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SofiaDefeat::
# 52 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Ohhh!\n"
# 53 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I did my best!$"
# 54 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 55 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SofiaPostBattle::
# 56 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I want to go home!$"
# 57 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 58 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_DudleyIntro::
# 59 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Hahaha!\n"
# 60 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Can you beat my power?$"
# 61 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 62 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_DudleyDefeat::
# 63 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Oops!\n"
# 64 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Outmuscled!$"
# 65 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 66 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_DudleyPostBattle::
# 67 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I go for power because I hate\n"
# 68 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "thinking.$"
# 69 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 70 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_CooperIntro::
# 71 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "You have a POKéDEX?\n"
# 72 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I want one, too.$"
# 73 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 74 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_CooperDefeat::
# 75 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Shoot!\n"
# 76 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I am so jealous!$"
# 77 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 78 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_CooperPostBattle::
# 79 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "When you finish your POKéDEX,\n"
# 80 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "can I have it?$"
# 81 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 82 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SteveIntro::
# 83 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Um… Do you know about POKéMON\n"
# 84 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "cosplay?$"
# 85 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 86 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SteveDefeat::
# 87 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Well, that's that.$"
# 88 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 89 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_StevePostBattle::
# 90 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "POKéMON cosplay is dressing up as\n"
# 91 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "POKéMON for fun.\p"
# 92 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "CLEFAIRY is a favorite.$"
# 93 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 94 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_AllenIntro::
# 95 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "My POKéMON techniques will leave\n"
# 96 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "you crying!$"
# 97 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 98 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_AllenDefeat::
# 99 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I give!\n"
# 100 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "You're a better technician!$"
# 101 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 102 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_AllenPostBattle::
# 103 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "In mountains, you'll often find\n"
# 104 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "ROCK-type POKéMON.$"
# 105 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 106 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_MarthaIntro::
# 107 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I don't often come here, but I will\n"
# 108 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "battle you.$"
# 109 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 110 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_MarthaDefeat::
# 111 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Oh!\n"
# 112 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I lost!$"
# 113 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 114 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_MarthaPostBattle::
# 115 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I like tiny POKéMON.\n"
# 116 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Big ones are too scary!$"
# 117 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 118 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_EricIntro::
# 119 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Hit me with your best shot!$"
# 120 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 121 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_EricDefeat::
# 122 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Fired away!$"
# 123 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 124 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_EricPostBattle::
# 125 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'll raise my POKéMON to beat\n"
# 126 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "yours, kid.$"
# 127 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 128 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_WinstonIntro::
# 129 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I draw illustrations of POKéMON\n"
# 130 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "when I'm home.$"
# 131 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 132 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_WinstonDefeat::
# 133 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Whew…\n"
# 134 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'm exhausted…$"
# 135 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 136 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_WinstonPostBattle::
# 137 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'm an artist, not a fighter.\n"
# 138 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'll go home to draw.$"
