# 1 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
SSAnne_1F_Corridor_Frlg_MapScripts::
# 3 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
SSAnne_1F_Corridor_EventScript_WorkerM::
# 6 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
# 7 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	end
# 8 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"

# 9 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
SSAnne_1F_Corridor_EventScript_Sailor::
# 10 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
# 11 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	end
# 12 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"

# 13 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
SSAnne_1F_Corridor_Text_LeStrongSilentType::
# 14 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "Bonjour!\n"
# 15 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "I am le waiter on this ship!\p"
# 16 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "I will be happy to serve you\n"
# 17 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "anything you please!\p"
# 18 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "… … …\n"
# 19 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "Ah! Le strong silent type!$"
# 20 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"

# 21 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
SSAnne_1F_Corridor_Text_PassengersAreRestless::
# 22 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "The passengers are restless from\n"
# 23 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "this long voyage.\p"
# 24 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "You might be challenged by the\n"
# 25 "data/maps/SSAnne_1F_Corridor_Frlg/scripts.pory"
	.string "more bored ones!$"
