# 1 "data/maps/Route19_Frlg/scripts.pory"

# 2 "data/maps/Route19_Frlg/scripts.pory"
Route19_Frlg_MapScripts::
# 3 "data/maps/Route19_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route19_Frlg/scripts.pory"

# 5 "data/maps/Route19_Frlg/scripts.pory"
Route19_EventScript_RouteSign::
# 6 "data/maps/Route19_Frlg/scripts.pory"
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/Route19_Frlg/scripts.pory"
	end
# 8 "data/maps/Route19_Frlg/scripts.pory"

# 9 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_RichardIntro::
# 10 "data/maps/Route19_Frlg/scripts.pory"
	.string "I have to exercise and warm up\n"
# 11 "data/maps/Route19_Frlg/scripts.pory"
	.string "before going out for a swim.$"
# 12 "data/maps/Route19_Frlg/scripts.pory"

# 13 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_RichardDefeat::
# 14 "data/maps/Route19_Frlg/scripts.pory"
	.string "All warmed up!$"
# 15 "data/maps/Route19_Frlg/scripts.pory"

# 16 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_RichardPostBattle::
# 17 "data/maps/Route19_Frlg/scripts.pory"
	.string "Thanks, kid!\n"
# 18 "data/maps/Route19_Frlg/scripts.pory"
	.string "I'm ready for a swim.$"
# 19 "data/maps/Route19_Frlg/scripts.pory"

# 20 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_ReeceIntro::
# 21 "data/maps/Route19_Frlg/scripts.pory"
	.string "Wait! Slow down!\n"
# 22 "data/maps/Route19_Frlg/scripts.pory"
	.string "You'll have a heart attack!$"
# 23 "data/maps/Route19_Frlg/scripts.pory"

# 24 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_ReeceDefeat::
# 25 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ooh!\n"
# 26 "data/maps/Route19_Frlg/scripts.pory"
	.string "That's chilly!$"
# 27 "data/maps/Route19_Frlg/scripts.pory"

# 28 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_ReecePostBattle::
# 29 "data/maps/Route19_Frlg/scripts.pory"
	.string "Watch out for TENTACOOL.\n"
# 30 "data/maps/Route19_Frlg/scripts.pory"
	.string "They sting so painfully.$"
# 31 "data/maps/Route19_Frlg/scripts.pory"

# 32 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_MatthewIntro::
# 33 "data/maps/Route19_Frlg/scripts.pory"
	.string "I love swimming!\n"
# 34 "data/maps/Route19_Frlg/scripts.pory"
	.string "What about you?$"
# 35 "data/maps/Route19_Frlg/scripts.pory"

# 36 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_MatthewDefeat::
# 37 "data/maps/Route19_Frlg/scripts.pory"
	.string "Belly flop!$"
# 38 "data/maps/Route19_Frlg/scripts.pory"

# 39 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_MatthewPostBattle::
# 40 "data/maps/Route19_Frlg/scripts.pory"
	.string "I can beat even marine POKéMON\n"
# 41 "data/maps/Route19_Frlg/scripts.pory"
	.string "at swimming.$"
# 42 "data/maps/Route19_Frlg/scripts.pory"

# 43 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_DouglasIntro::
# 44 "data/maps/Route19_Frlg/scripts.pory"
	.string "What's beyond the horizon?$"
# 45 "data/maps/Route19_Frlg/scripts.pory"

# 46 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_DouglasDefeat::
# 47 "data/maps/Route19_Frlg/scripts.pory"
	.string "Glub!$"
# 48 "data/maps/Route19_Frlg/scripts.pory"

# 49 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_DouglasPostBattle::
# 50 "data/maps/Route19_Frlg/scripts.pory"
	.string "I see a couple of islands over\n"
# 51 "data/maps/Route19_Frlg/scripts.pory"
	.string "yonder!$"
# 52 "data/maps/Route19_Frlg/scripts.pory"

# 53 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_DavidIntro::
# 54 "data/maps/Route19_Frlg/scripts.pory"
	.string "I tried diving for POKéMON, but it\n"
# 55 "data/maps/Route19_Frlg/scripts.pory"
	.string "was a no-go.$"
# 56 "data/maps/Route19_Frlg/scripts.pory"

# 57 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_DavidDefeat::
# 58 "data/maps/Route19_Frlg/scripts.pory"
	.string "Help!$"
# 59 "data/maps/Route19_Frlg/scripts.pory"

# 60 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_DavidPostBattle::
# 61 "data/maps/Route19_Frlg/scripts.pory"
	.string "I guess you have to fish for sea\n"
# 62 "data/maps/Route19_Frlg/scripts.pory"
	.string "POKéMON.$"
# 63 "data/maps/Route19_Frlg/scripts.pory"

# 64 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_TonyIntro::
# 65 "data/maps/Route19_Frlg/scripts.pory"
	.string "I look at the sea to forget all\n"
# 66 "data/maps/Route19_Frlg/scripts.pory"
	.string "the bad things that happened.$"
# 67 "data/maps/Route19_Frlg/scripts.pory"

# 68 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_TonyDefeat::
# 69 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ooh!\n"
# 70 "data/maps/Route19_Frlg/scripts.pory"
	.string "Traumatic!$"
# 71 "data/maps/Route19_Frlg/scripts.pory"

# 72 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_TonyPostBattle::
# 73 "data/maps/Route19_Frlg/scripts.pory"
	.string "I'm looking at the sea to forget\n"
# 74 "data/maps/Route19_Frlg/scripts.pory"
	.string "the bad thing that happened!$"
# 75 "data/maps/Route19_Frlg/scripts.pory"

# 76 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AnyaIntro::
# 77 "data/maps/Route19_Frlg/scripts.pory"
	.string "Oh, I just love your ride!\n"
# 78 "data/maps/Route19_Frlg/scripts.pory"
	.string "Can I have it if I win?$"
# 79 "data/maps/Route19_Frlg/scripts.pory"

# 80 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AnyaDefeat::
# 81 "data/maps/Route19_Frlg/scripts.pory"
	.string "Oh! I lost!$"
# 82 "data/maps/Route19_Frlg/scripts.pory"

# 83 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AnyaPostBattle::
# 84 "data/maps/Route19_Frlg/scripts.pory"
	.string "It's still a long way to go to\n"
# 85 "data/maps/Route19_Frlg/scripts.pory"
	.string "SEAFOAM ISLANDS…\p"
# 86 "data/maps/Route19_Frlg/scripts.pory"
	.string "I want to go back to FUCHSIA…$"
# 87 "data/maps/Route19_Frlg/scripts.pory"

# 88 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AliceIntro::
# 89 "data/maps/Route19_Frlg/scripts.pory"
	.string "Swimming's great!\n"
# 90 "data/maps/Route19_Frlg/scripts.pory"
	.string "Sunburns aren't!$"
# 91 "data/maps/Route19_Frlg/scripts.pory"

# 92 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AliceDefeat::
# 93 "data/maps/Route19_Frlg/scripts.pory"
	.string "Shocker!$"
# 94 "data/maps/Route19_Frlg/scripts.pory"

# 95 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AlicePostBattle::
# 96 "data/maps/Route19_Frlg/scripts.pory"
	.string "My boyfriend wanted to swim to\n"
# 97 "data/maps/Route19_Frlg/scripts.pory"
	.string "SEAFOAM ISLANDS.$"
# 98 "data/maps/Route19_Frlg/scripts.pory"

# 99 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AxleIntro::
# 100 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ahoy, there!\n"
# 101 "data/maps/Route19_Frlg/scripts.pory"
	.string "These waters are treacherous!$"
# 102 "data/maps/Route19_Frlg/scripts.pory"

# 103 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AxleDefeat::
# 104 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ooh!\n"
# 105 "data/maps/Route19_Frlg/scripts.pory"
	.string "Dangerous!$"
# 106 "data/maps/Route19_Frlg/scripts.pory"

# 107 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_AxlePostBattle::
# 108 "data/maps/Route19_Frlg/scripts.pory"
	.string "M-my legs! They cramped up!\n"
# 109 "data/maps/Route19_Frlg/scripts.pory"
	.string "Glub, glub…$"
# 110 "data/maps/Route19_Frlg/scripts.pory"

# 111 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_ConnieIntro::
# 112 "data/maps/Route19_Frlg/scripts.pory"
	.string "I swam here with my friends…\n"
# 113 "data/maps/Route19_Frlg/scripts.pory"
	.string "I'm tired…$"
# 114 "data/maps/Route19_Frlg/scripts.pory"

# 115 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_ConnieDefeat::
# 116 "data/maps/Route19_Frlg/scripts.pory"
	.string "I'm exhausted…$"
# 117 "data/maps/Route19_Frlg/scripts.pory"

# 118 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_ConniePostBattle::
# 119 "data/maps/Route19_Frlg/scripts.pory"
	.string "If I were to ride a POKéMON on\n"
# 120 "data/maps/Route19_Frlg/scripts.pory"
	.string "the sea, I'd like a LAPRAS.\p"
# 121 "data/maps/Route19_Frlg/scripts.pory"
	.string "LAPRAS is so big, I bet it\n"
# 122 "data/maps/Route19_Frlg/scripts.pory"
	.string "would keep me dry on water.$"
# 123 "data/maps/Route19_Frlg/scripts.pory"

# 124 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_RouteSign::
# 125 "data/maps/Route19_Frlg/scripts.pory"
	.string "SEA ROUTE 19\n"
# 126 "data/maps/Route19_Frlg/scripts.pory"
	.string "FUCHSIA CITY - SEAFOAM ISLANDS$"
# 127 "data/maps/Route19_Frlg/scripts.pory"

# 128 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LiaIntro::
# 129 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: I'm looking after my brother.\n"
# 130 "data/maps/Route19_Frlg/scripts.pory"
	.string "He just became a TRAINER.$"
# 131 "data/maps/Route19_Frlg/scripts.pory"

# 132 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LiaDefeat::
# 133 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: That's no way to treat my\n"
# 134 "data/maps/Route19_Frlg/scripts.pory"
	.string "little brother!$"
# 135 "data/maps/Route19_Frlg/scripts.pory"

# 136 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LiaPostBattle::
# 137 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: Do you have a younger\n"
# 138 "data/maps/Route19_Frlg/scripts.pory"
	.string "brother?\p"
# 139 "data/maps/Route19_Frlg/scripts.pory"
	.string "I hope you're teaching him all\n"
# 140 "data/maps/Route19_Frlg/scripts.pory"
	.string "sorts of things.$"
# 141 "data/maps/Route19_Frlg/scripts.pory"

# 142 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LiaNotEnoughMons::
# 143 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: I want to battle together\n"
# 144 "data/maps/Route19_Frlg/scripts.pory"
	.string "with my little brother.\p"
# 145 "data/maps/Route19_Frlg/scripts.pory"
	.string "Don't you have two POKéMON?$"
# 146 "data/maps/Route19_Frlg/scripts.pory"

# 147 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LucIntro::
# 148 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: My big sis taught me how\n"
# 149 "data/maps/Route19_Frlg/scripts.pory"
	.string "to swim and train POKéMON.$"
# 150 "data/maps/Route19_Frlg/scripts.pory"

# 151 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LucDefeat::
# 152 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: Oh, wow!\n"
# 153 "data/maps/Route19_Frlg/scripts.pory"
	.string "Someone tougher than my big sis!$"
# 154 "data/maps/Route19_Frlg/scripts.pory"

# 155 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LucPostBattle::
# 156 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: My big sis is strong and nice.\n"
# 157 "data/maps/Route19_Frlg/scripts.pory"
	.string "I think she's awesome!$"
# 158 "data/maps/Route19_Frlg/scripts.pory"

# 159 "data/maps/Route19_Frlg/scripts.pory"
Route19_Text_LucNotEnoughMons::
# 160 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: I don't want to if I can't\n"
# 161 "data/maps/Route19_Frlg/scripts.pory"
	.string "battle you with my big sis.\p"
# 162 "data/maps/Route19_Frlg/scripts.pory"
	.string "Don't you have two POKéMON?$"
