# 1 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"

# 2 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
UndergroundPath_WestEntrance_Frlg_MapScripts::
# 3 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"

# 5 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
UndergroundPath_WestEntrance_EventScript_BaldingMan::
# 6 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
	msgbox UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon, MSGBOX_NPC
# 7 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
	end
# 8 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"

# 9 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon::
# 10 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
	.string "I heard a sleepy POKéMON appeared\n"
# 11 "data/maps/UndergroundPath_WestEntrance_Frlg/scripts.pory"
	.string "out near CELADON CITY, too.$"
