# 1 "data/maps/Route21_North_Frlg/scripts.pory"

# 2 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Frlg_MapScripts::
# 3 "data/maps/Route21_North_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route21_North_Frlg/scripts.pory"

# 5 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_RonaldIntro::
# 6 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "You want to know if the fish are\n"
# 7 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "biting?$"
# 8 "data/maps/Route21_North_Frlg/scripts.pory"

# 9 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_RonaldDefeat::
# 10 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Dang!$"
# 11 "data/maps/Route21_North_Frlg/scripts.pory"

# 12 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_RonaldPostBattle::
# 13 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "I can't catch anything good.\n"
# 14 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Not one good POKéMON to be had!$"
# 15 "data/maps/Route21_North_Frlg/scripts.pory"

# 16 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_WadeIntro::
# 17 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "I got a big haul!\n"
# 18 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Wanna go for it?$"
# 19 "data/maps/Route21_North_Frlg/scripts.pory"

# 20 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_WadeDefeat::
# 21 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Heheh, MAGIKARP just don't make\n"
# 22 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "the grade, do they?$"
# 23 "data/maps/Route21_North_Frlg/scripts.pory"

# 24 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_WadePostBattle::
# 25 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "I seem to only catch MAGIKARP!$"
# 26 "data/maps/Route21_North_Frlg/scripts.pory"

# 27 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_SpencerIntro::
# 28 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "The sea cleanses my body and soul!$"
# 29 "data/maps/Route21_North_Frlg/scripts.pory"

# 30 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_SpencerDefeat::
# 31 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Ayah!$"
# 32 "data/maps/Route21_North_Frlg/scripts.pory"

# 33 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_SpencerPostBattle::
# 34 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "The sea is great and all, but I\n"
# 35 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "like the mountains, too.$"
# 36 "data/maps/Route21_North_Frlg/scripts.pory"

# 37 "data/maps/Route21_North_Frlg/scripts.pory"
@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
# 38 "data/maps/Route21_North_Frlg/scripts.pory"
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
# 39 "data/maps/Route21_North_Frlg/scripts.pory"
@ Interestingly they did add a rematch intro text for this trainer
# 40 "data/maps/Route21_North_Frlg/scripts.pory"
@ English translations from RB are listed
# 41 "data/maps/Route21_North_Frlg/scripts.pory"

# 42 "data/maps/Route21_North_Frlg/scripts.pory"
@ "What's wrong with me swimming?"
# 43 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_CueBallIntro::
# 44 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "おれだって　たまには\n"
# 45 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "およぎに　くるぜ！$"
# 46 "data/maps/Route21_North_Frlg/scripts.pory"

# 47 "data/maps/Route21_North_Frlg/scripts.pory"
@ "Cheap shot!"
# 48 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_CueBallDefeat::
# 49 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "ぐわわ！$"
# 50 "data/maps/Route21_North_Frlg/scripts.pory"

# 51 "data/maps/Route21_North_Frlg/scripts.pory"
@ "I look like what? A studded inner tube? Get lost!"
# 52 "data/maps/Route21_North_Frlg/scripts.pory"
Route21_North_Text_CueBallPostBattle::
# 53 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "うきやすそう　だと？\n"
# 54 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "うるせー　おおきな　おせわだッ！$"
