# 1 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
SSAnne_2F_Room6_Frlg_MapScripts::
# 3 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
SSAnne_2F_Room6_EventScript_Woman1::
# 6 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
# 7 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	end
# 8 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"

# 9 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
SSAnne_2F_Room6_EventScript_Woman2::
# 10 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
# 11 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	end
# 12 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"

# 13 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
# 14 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	.string "The CAPTAIN said he's awfully sick.\n"
# 15 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	.string "He was all pale.$"
# 16 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"

# 17 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
# 18 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	.string "I hear many people get seasick.$"
