# 1 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 2 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Frlg_MapScripts::
# 3 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 5 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
# 6 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	end
# 8 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 9 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
# 10 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Kyahaha!\n"
# 11 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "I'll flick you away effortlessly!$"
# 12 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 13 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
# 14 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Tch!\n"
# 15 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Too strong for me!$"
# 16 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 17 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
# 18 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "What's that?\n"
# 19 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "I don't act the way I look?\p"
# 20 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Heh, that's a part of my strategy!$"
# 21 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 22 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
# 23 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Howdy!\n"
# 24 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Are you a member of my fan club?$"
# 25 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 26 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
# 27 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Oh, so you're not a fan…\p"
# 28 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Well, I can change that.\n"
# 29 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Let me sing for you!$"
# 30 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 31 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
# 32 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Lalalah…\n"
# 33 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "My POKéMON, I send them out,\l"
# 34 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "all the girls scream and shout!$"
# 35 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 36 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
# 37 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "This island is too spread out…\n"
# 38 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "It's not easy patrolling the place.$"
# 39 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 40 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
# 41 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Uh-huh…$"
# 42 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 43 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
# 44 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "TRAINERS like you from cities,\n"
# 45 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "they sure are tough.\p"
# 46 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "You'll be headed for the TOWER,\n"
# 47 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "won't you?$"
# 48 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 49 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
# 50 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "I punish people who abuse\n"
# 51 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "POKéMON!$"
# 52 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 53 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
# 54 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "You don't seem to be a problem\n"
# 55 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "TRAINER.$"
# 56 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 57 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
# 58 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "If you treat your POKéMON with\n"
# 59 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "kindness, they'll understand.$"
# 60 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 61 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
# 62 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "EVE: I'll team up with JON and\n"
# 63 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "battle together.$"
# 64 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 65 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
# 66 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "EVE: Me and JON, we lost.\n"
# 67 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Ehehe.$"
# 68 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 69 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
# 70 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "EVE: I'm going to work harder with\n"
# 71 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "JON.$"
# 72 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 73 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
# 74 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "EVE: I want to team up with JON\n"
# 75 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "when I battle you.\p"
# 76 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "Come back with two POKéMON, okay?$"
# 77 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 78 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
# 79 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "JON: When I'm with EVE, it feels\n"
# 80 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "like we could never lose.$"
# 81 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 82 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
# 83 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "JON: When I'm with EVE,\n"
# 84 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "it doesn't feel like I've lost!$"
# 85 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 86 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
# 87 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "JON: When I'm with EVE, I feel\n"
# 88 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "giddy whether I win or lose.\p"
# 89 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "It's magical!$"
# 90 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 91 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
# 92 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "JON: If it's with EVE, I'll be\n"
# 93 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "happy to battle with you.\p"
# 94 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "So, I'd like to make it a\n"
# 95 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "two-on-two battle, if I may.$"
# 96 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"

# 97 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
# 98 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "SEVAULT CANYON ENTRANCE\p"
# 99 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "TRAINERS are asked to refrain from\n"
# 100 "data/maps/SevenIsland_SevaultCanyon_Entrance_Frlg/scripts.pory"
	.string "damaging plants in the CANYON.$"
