# 1 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_RestHouse_Frlg_MapScripts::
# 3 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_RestHouse_EventScript_Rocker::
# 6 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
# 7 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	end
# 8 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 9 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_RestHouse_EventScript_Scientist::
# 10 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
# 11 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	end
# 12 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 13 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_RestHouse_EventScript_BaldingMan::
# 14 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
# 15 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	end
# 16 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_Text_HowManyDidYouCatch::
# 18 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.string "How many did you catch?\n"
# 19 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.string "I'm bushed from the effort!$"
# 20 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 21 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_Text_CaughtChanseyAllWorthwhile::
# 22 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.string "I caught a CHANSEY!\p"
# 23 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.string "That makes this all worthwhile.$"
# 24 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"

# 25 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
SafariZone_East_Text_TiredFromAllTheFun::
# 26 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.string "Whew!\n"
# 27 "data/maps/SafariZone_East_RestHouse_Frlg/scripts.pory"
	.string "I'm tired from all the fun!$"
