# 1 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"

# 2 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
UndergroundPath_EastEntrance_Frlg_MapScripts::
# 3 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"

# 5 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
UndergroundPath_EastEntrance_EventScript_Woman::
# 6 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
	msgbox UndergroundPath_EastEntrance_Text_DoYouGoToCeladonDeptStore, MSGBOX_NPC
# 7 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
	end
# 8 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"

# 9 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
UndergroundPath_EastEntrance_Text_DoYouGoToCeladonDeptStore::
# 10 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
	.string "The DEPARTMENT STORE in CELADON\n"
# 11 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
	.string "has a great selection.\p"
# 12 "data/maps/UndergroundPath_EastEntrance_Frlg/scripts.pory"
	.string "Do you go there very often?$"
