# 1 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 2 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_Frlg_MapScripts::
# 3 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 5 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_EventScript_RocketChief::
# 6 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
# 7 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	end
# 8 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 9 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_EventScript_Rocket1::
# 10 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
# 11 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	end
# 12 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 13 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_EventScript_Rocket2::
# 14 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
# 15 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	end
# 16 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 17 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_Text_SlotsReelInTheDough::
# 18 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "Hehehe!\p"
# 19 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "The slots just reel in the dough,\n"
# 20 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "big-time!$"
# 21 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 22 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
# 23 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "CHIEF!\p"
# 24 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "We just shipped two thousand\n"
# 25 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "more POKéMON as slot prizes\l"
# 26 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "again today!$"
# 27 "data/maps/CeladonCity_House1_Frlg/scripts.pory"

# 28 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
CeladonCity_House1_Text_DontTouchGameCornerPoster::
# 29 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "Don't touch the poster at the GAME\n"
# 30 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "CORNER!\p"
# 31 "data/maps/CeladonCity_House1_Frlg/scripts.pory"
	.string "There's no secret switch behind it!$"
