# 1 "data/maps/PewterCity_House2_Frlg/scripts.pory"

# 2 "data/maps/PewterCity_House2_Frlg/scripts.pory"
PewterCity_House2_Frlg_MapScripts::
# 3 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/PewterCity_House2_Frlg/scripts.pory"

# 5 "data/maps/PewterCity_House2_Frlg/scripts.pory"
PewterCity_House2_EventScript_OldMan::
# 6 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
# 7 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	end
# 8 "data/maps/PewterCity_House2_Frlg/scripts.pory"

# 9 "data/maps/PewterCity_House2_Frlg/scripts.pory"
PewterCity_House2_EventScript_LittleBoy::
# 10 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
# 11 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	end
# 12 "data/maps/PewterCity_House2_Frlg/scripts.pory"

# 13 "data/maps/PewterCity_House2_Frlg/scripts.pory"
PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
# 14 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "POKéMON learn new techniques as\n"
# 15 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "they grow.\p"
# 16 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "But some moves must be taught to\n"
# 17 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "them by people.$"
# 18 "data/maps/PewterCity_House2_Frlg/scripts.pory"

# 19 "data/maps/PewterCity_House2_Frlg/scripts.pory"
PewterCity_House2_Text_MonsEasierCatchIfStatused::
# 20 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "A POKéMON becomes easier to \n"
# 21 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "catch if it has a status problem.\p"
# 22 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "Sleep, poison, burn, or paralysis…\n"
# 23 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "Those are all effective.\p"
# 24 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "But catching POKéMON is never\n"
# 25 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "a sure thing!$"
