# 1 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 2 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
# 3 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 5 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
# 6 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
# 7 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	end
# 8 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 9 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
# 10 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
# 11 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	end
# 12 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 13 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
# 14 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
# 15 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	end
# 16 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 17 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
# 18 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "Many POKéMON live only in forests \n"
# 19 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "and caves.\p"
# 20 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "You need to be persistent and look\n"
# 21 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "everywhere to get different kinds.$"
# 22 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 23 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
# 24 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "Have you noticed the skinny trees\n"
# 25 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "on the roadside?\p"
# 26 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "They can be cut down by a special\n"
# 27 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "POKéMON move, I hear.$"
# 28 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"

# 29 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
# 30 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "Do you know the evolution-cancel\n"
# 31 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "technique?\p"
# 32 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "When a POKéMON is evolving, you\n"
# 33 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "can stop the process.\p"
# 34 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "It's a technique for raising\n"
# 35 "data/maps/Route2_ViridianForest_NorthEntrance_Frlg/scripts.pory"
	.string "POKéMON the way they are.$"
