# 1 "data/maps/Route17_Frlg/scripts.pory"

# 2 "data/maps/Route17_Frlg/scripts.pory"
Route17_Frlg_MapScripts::
# 3 "data/maps/Route17_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route17_Frlg/scripts.pory"

# 5 "data/maps/Route17_Frlg/scripts.pory"
Route17_EventScript_ItemsNotice::
# 6 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
# 7 "data/maps/Route17_Frlg/scripts.pory"
	end
# 8 "data/maps/Route17_Frlg/scripts.pory"

# 9 "data/maps/Route17_Frlg/scripts.pory"
Route17_EventScript_TrainerTips1::
# 10 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
# 11 "data/maps/Route17_Frlg/scripts.pory"
	end
# 12 "data/maps/Route17_Frlg/scripts.pory"

# 13 "data/maps/Route17_Frlg/scripts.pory"
Route17_EventScript_TrainerTips2::
# 14 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
# 15 "data/maps/Route17_Frlg/scripts.pory"
	end
# 16 "data/maps/Route17_Frlg/scripts.pory"

# 17 "data/maps/Route17_Frlg/scripts.pory"
Route17_EventScript_RouteSign::
# 18 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
# 19 "data/maps/Route17_Frlg/scripts.pory"
	end
# 20 "data/maps/Route17_Frlg/scripts.pory"

# 21 "data/maps/Route17_Frlg/scripts.pory"
Route17_EventScript_BallsNotice::
# 22 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
# 23 "data/maps/Route17_Frlg/scripts.pory"
	end
# 24 "data/maps/Route17_Frlg/scripts.pory"

# 25 "data/maps/Route17_Frlg/scripts.pory"
Route17_EventScript_CyclingRoadSign::
# 26 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
# 27 "data/maps/Route17_Frlg/scripts.pory"
	end
# 28 "data/maps/Route17_Frlg/scripts.pory"

# 29 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_RaulIntro::
# 30 "data/maps/Route17_Frlg/scripts.pory"
	.string "There's no getting rich quick in\n"
# 31 "data/maps/Route17_Frlg/scripts.pory"
	.string "battling kids.$"
# 32 "data/maps/Route17_Frlg/scripts.pory"

# 33 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_RaulDefeat::
# 34 "data/maps/Route17_Frlg/scripts.pory"
	.string "Burned out!$"
# 35 "data/maps/Route17_Frlg/scripts.pory"

# 36 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_RaulPostBattle::
# 37 "data/maps/Route17_Frlg/scripts.pory"
	.string "You can find good stuff lying\n"
# 38 "data/maps/Route17_Frlg/scripts.pory"
	.string "around on CYCLING ROAD.\p"
# 39 "data/maps/Route17_Frlg/scripts.pory"
	.string "There's good money in picking them\n"
# 40 "data/maps/Route17_Frlg/scripts.pory"
	.string "up and selling them.$"
# 41 "data/maps/Route17_Frlg/scripts.pory"

# 42 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_IsaiahIntro::
# 43 "data/maps/Route17_Frlg/scripts.pory"
	.string "I'm mighty proud of my bod, kiddo.\n"
# 44 "data/maps/Route17_Frlg/scripts.pory"
	.string "Come on!$"
# 45 "data/maps/Route17_Frlg/scripts.pory"

# 46 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_IsaiahDefeat::
# 47 "data/maps/Route17_Frlg/scripts.pory"
	.string "Whoo!$"
# 48 "data/maps/Route17_Frlg/scripts.pory"

# 49 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_IsaiahPostBattle::
# 50 "data/maps/Route17_Frlg/scripts.pory"
	.string "I could belly-bump you outta\n"
# 51 "data/maps/Route17_Frlg/scripts.pory"
	.string "here!$"
# 52 "data/maps/Route17_Frlg/scripts.pory"

# 53 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_VirgilIntro::
# 54 "data/maps/Route17_Frlg/scripts.pory"
	.string "You heading to FUCHSIA?$"
# 55 "data/maps/Route17_Frlg/scripts.pory"

# 56 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_VirgilDefeat::
# 57 "data/maps/Route17_Frlg/scripts.pory"
	.string "Crash and burn!$"
# 58 "data/maps/Route17_Frlg/scripts.pory"

# 59 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_VirgilPostBattle::
# 60 "data/maps/Route17_Frlg/scripts.pory"
	.string "I love racing downhill!$"
# 61 "data/maps/Route17_Frlg/scripts.pory"

# 62 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_BillyIntro::
# 63 "data/maps/Route17_Frlg/scripts.pory"
	.string "We're BIKERS!\n"
# 64 "data/maps/Route17_Frlg/scripts.pory"
	.string "We rule the roads, man!$"
# 65 "data/maps/Route17_Frlg/scripts.pory"

# 66 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_BillyDefeat::
# 67 "data/maps/Route17_Frlg/scripts.pory"
	.string "Smoked!$"
# 68 "data/maps/Route17_Frlg/scripts.pory"

# 69 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_BillyPostBattle::
# 70 "data/maps/Route17_Frlg/scripts.pory"
	.string "Are you looking for adventure?$"
# 71 "data/maps/Route17_Frlg/scripts.pory"

# 72 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_NikolasIntro::
# 73 "data/maps/Route17_Frlg/scripts.pory"
	.string "Let VOLTORB electrify you!$"
# 74 "data/maps/Route17_Frlg/scripts.pory"

# 75 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_NikolasDefeat::
# 76 "data/maps/Route17_Frlg/scripts.pory"
	.string "Grounded out!$"
# 77 "data/maps/Route17_Frlg/scripts.pory"

# 78 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_NikolasPostBattle::
# 79 "data/maps/Route17_Frlg/scripts.pory"
	.string "I got my VOLTORB at the abandoned\n"
# 80 "data/maps/Route17_Frlg/scripts.pory"
	.string "POWER PLANT.$"
# 81 "data/maps/Route17_Frlg/scripts.pory"

# 82 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_ZeekIntro::
# 83 "data/maps/Route17_Frlg/scripts.pory"
	.string "I leveled up my POKéMON, but it\n"
# 84 "data/maps/Route17_Frlg/scripts.pory"
	.string "won't evolve. Why?$"
# 85 "data/maps/Route17_Frlg/scripts.pory"

# 86 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_ZeekDefeat::
# 87 "data/maps/Route17_Frlg/scripts.pory"
	.string "Why, you!$"
# 88 "data/maps/Route17_Frlg/scripts.pory"

# 89 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_ZeekPostBattle::
# 90 "data/maps/Route17_Frlg/scripts.pory"
	.string "Maybe some POKéMON need element\n"
# 91 "data/maps/Route17_Frlg/scripts.pory"
	.string "STONES to evolve.$"
# 92 "data/maps/Route17_Frlg/scripts.pory"

# 93 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_JamalIntro::
# 94 "data/maps/Route17_Frlg/scripts.pory"
	.string "I need a little exercise!$"
# 95 "data/maps/Route17_Frlg/scripts.pory"

# 96 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_JamalDefeat::
# 97 "data/maps/Route17_Frlg/scripts.pory"
	.string "Whew!\n"
# 98 "data/maps/Route17_Frlg/scripts.pory"
	.string "Good workout!$"
# 99 "data/maps/Route17_Frlg/scripts.pory"

# 100 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_JamalPostBattle::
# 101 "data/maps/Route17_Frlg/scripts.pory"
	.string "I'm sure I lost weight there!$"
# 102 "data/maps/Route17_Frlg/scripts.pory"

# 103 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_CoreyIntro::
# 104 "data/maps/Route17_Frlg/scripts.pory"
	.string "Be a rebel!$"
# 105 "data/maps/Route17_Frlg/scripts.pory"

# 106 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_CoreyDefeat::
# 107 "data/maps/Route17_Frlg/scripts.pory"
	.string "Aaaargh!$"
# 108 "data/maps/Route17_Frlg/scripts.pory"

# 109 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_CoreyPostBattle::
# 110 "data/maps/Route17_Frlg/scripts.pory"
	.string "Be ready to fight for your beliefs!$"
# 111 "data/maps/Route17_Frlg/scripts.pory"

# 112 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_JaxonIntro::
# 113 "data/maps/Route17_Frlg/scripts.pory"
	.string "Nice BIKE!\n"
# 114 "data/maps/Route17_Frlg/scripts.pory"
	.string "How's it handle?$"
# 115 "data/maps/Route17_Frlg/scripts.pory"

# 116 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_JaxonDefeat::
# 117 "data/maps/Route17_Frlg/scripts.pory"
	.string "Shoot!$"
# 118 "data/maps/Route17_Frlg/scripts.pory"

# 119 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_JaxonPostBattle::
# 120 "data/maps/Route17_Frlg/scripts.pory"
	.string "The slope makes it hard to steer.$"
# 121 "data/maps/Route17_Frlg/scripts.pory"

# 122 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_WilliamIntro::
# 123 "data/maps/Route17_Frlg/scripts.pory"
	.string "Get lost, kid!\n"
# 124 "data/maps/Route17_Frlg/scripts.pory"
	.string "I'm bushed!$"
# 125 "data/maps/Route17_Frlg/scripts.pory"

# 126 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_WilliamDefeat::
# 127 "data/maps/Route17_Frlg/scripts.pory"
	.string "Are you satisfied?$"
# 128 "data/maps/Route17_Frlg/scripts.pory"

# 129 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_WilliamPostBattle::
# 130 "data/maps/Route17_Frlg/scripts.pory"
	.string "I need to catch a few z's!$"
# 131 "data/maps/Route17_Frlg/scripts.pory"

# 132 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_WatchOutForDiscardedItems::
# 133 "data/maps/Route17_Frlg/scripts.pory"
	.string "It's a notice.\p"
# 134 "data/maps/Route17_Frlg/scripts.pory"
	.string "Watch out for discarded items.$"
# 135 "data/maps/Route17_Frlg/scripts.pory"

# 136 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_SameSpeciesGrowDifferentRates::
# 137 "data/maps/Route17_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 138 "data/maps/Route17_Frlg/scripts.pory"
	.string "All POKéMON are unique.\p"
# 139 "data/maps/Route17_Frlg/scripts.pory"
	.string "Even POKéMON of the same species\n"
# 140 "data/maps/Route17_Frlg/scripts.pory"
	.string "and level grow at different rates.$"
# 141 "data/maps/Route17_Frlg/scripts.pory"

# 142 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_PressBToStayInPlace::
# 143 "data/maps/Route17_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 144 "data/maps/Route17_Frlg/scripts.pory"
	.string "Press the B Button to stay in place\n"
# 145 "data/maps/Route17_Frlg/scripts.pory"
	.string "while on a slope.$"
# 146 "data/maps/Route17_Frlg/scripts.pory"

# 147 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_RouteSign::
# 148 "data/maps/Route17_Frlg/scripts.pory"
	.string "ROUTE 17\n"
# 149 "data/maps/Route17_Frlg/scripts.pory"
	.string "CELADON CITY - FUCHSIA CITY$"
# 150 "data/maps/Route17_Frlg/scripts.pory"

# 151 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_DontThrowGameThrowBalls::
# 152 "data/maps/Route17_Frlg/scripts.pory"
	.string "It's a notice!\p"
# 153 "data/maps/Route17_Frlg/scripts.pory"
	.string "Don't throw the game, throw POKé\n"
# 154 "data/maps/Route17_Frlg/scripts.pory"
	.string "BALLS instead!$"
# 155 "data/maps/Route17_Frlg/scripts.pory"

# 156 "data/maps/Route17_Frlg/scripts.pory"
Route17_Text_CyclingRoadSign::
# 157 "data/maps/Route17_Frlg/scripts.pory"
	.string "CYCLING ROAD\n"
# 158 "data/maps/Route17_Frlg/scripts.pory"
	.string "Slope ends here!$"
