# 1 "data/maps/Route6_Frlg/scripts.pory"

# 2 "data/maps/Route6_Frlg/scripts.pory"
Route6_Frlg_MapScripts::
# 3 "data/maps/Route6_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route6_Frlg/scripts.pory"

# 5 "data/maps/Route6_Frlg/scripts.pory"
Route6_EventScript_UndergroundPathSign::
# 6 "data/maps/Route6_Frlg/scripts.pory"
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
# 7 "data/maps/Route6_Frlg/scripts.pory"
	end
# 8 "data/maps/Route6_Frlg/scripts.pory"

# 9 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_RickyIntro::
# 10 "data/maps/Route6_Frlg/scripts.pory"
	.string "Who's there?\n"
# 11 "data/maps/Route6_Frlg/scripts.pory"
	.string "Quit listening in on us!$"
# 12 "data/maps/Route6_Frlg/scripts.pory"

# 13 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_RickyDefeat::
# 14 "data/maps/Route6_Frlg/scripts.pory"
	.string "I just can't win!$"
# 15 "data/maps/Route6_Frlg/scripts.pory"

# 16 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_RickyPostBattle::
# 17 "data/maps/Route6_Frlg/scripts.pory"
	.string "Whisper…\n"
# 18 "data/maps/Route6_Frlg/scripts.pory"
	.string "Whisper…$"
# 19 "data/maps/Route6_Frlg/scripts.pory"

# 20 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_NancyIntro::
# 21 "data/maps/Route6_Frlg/scripts.pory"
	.string "Excuse me!\n"
# 22 "data/maps/Route6_Frlg/scripts.pory"
	.string "This is a private conversation!$"
# 23 "data/maps/Route6_Frlg/scripts.pory"

# 24 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_NancyDefeat::
# 25 "data/maps/Route6_Frlg/scripts.pory"
	.string "Ugh!\n"
# 26 "data/maps/Route6_Frlg/scripts.pory"
	.string "I hate losing.$"
# 27 "data/maps/Route6_Frlg/scripts.pory"

# 28 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_NancyPostBattle::
# 29 "data/maps/Route6_Frlg/scripts.pory"
	.string "Whisper…\n"
# 30 "data/maps/Route6_Frlg/scripts.pory"
	.string "Whisper…$"
# 31 "data/maps/Route6_Frlg/scripts.pory"

# 32 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_KeigoIntro::
# 33 "data/maps/Route6_Frlg/scripts.pory"
	.string "There aren't many bugs out here.$"
# 34 "data/maps/Route6_Frlg/scripts.pory"

# 35 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_KeigoDefeat::
# 36 "data/maps/Route6_Frlg/scripts.pory"
	.string "No!\n"
# 37 "data/maps/Route6_Frlg/scripts.pory"
	.string "You're kidding!$"
# 38 "data/maps/Route6_Frlg/scripts.pory"

# 39 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_KeigoPostBattle::
# 40 "data/maps/Route6_Frlg/scripts.pory"
	.string "I like bugs, so I'm going back to\n"
# 41 "data/maps/Route6_Frlg/scripts.pory"
	.string "VIRIDIAN FOREST.$"
# 42 "data/maps/Route6_Frlg/scripts.pory"

# 43 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_JeffIntro::
# 44 "data/maps/Route6_Frlg/scripts.pory"
	.string "Huh?\n"
# 45 "data/maps/Route6_Frlg/scripts.pory"
	.string "You want to talk to me?$"
# 46 "data/maps/Route6_Frlg/scripts.pory"

# 47 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_JeffDefeat::
# 48 "data/maps/Route6_Frlg/scripts.pory"
	.string "This stinks…\n"
# 49 "data/maps/Route6_Frlg/scripts.pory"
	.string "I couldn't beat your challenge…$"
# 50 "data/maps/Route6_Frlg/scripts.pory"

# 51 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_JeffPostBattle::
# 52 "data/maps/Route6_Frlg/scripts.pory"
	.string "I should bring more POKéMON with\n"
# 53 "data/maps/Route6_Frlg/scripts.pory"
	.string "me. I'll feel safer that way.$"
# 54 "data/maps/Route6_Frlg/scripts.pory"

# 55 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_IsabelleIntro::
# 56 "data/maps/Route6_Frlg/scripts.pory"
	.string "Me?\n"
# 57 "data/maps/Route6_Frlg/scripts.pory"
	.string "Well, okay. I'll play!$"
# 58 "data/maps/Route6_Frlg/scripts.pory"

# 59 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_IsabelleDefeat::
# 60 "data/maps/Route6_Frlg/scripts.pory"
	.string "Things just didn't work…$"
# 61 "data/maps/Route6_Frlg/scripts.pory"

# 62 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_IsabellePostBattle::
# 63 "data/maps/Route6_Frlg/scripts.pory"
	.string "I want to get stronger.\n"
# 64 "data/maps/Route6_Frlg/scripts.pory"
	.string "What's your secret?$"
# 65 "data/maps/Route6_Frlg/scripts.pory"

# 66 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_ElijahIntro::
# 67 "data/maps/Route6_Frlg/scripts.pory"
	.string "I've never seen you around.\n"
# 68 "data/maps/Route6_Frlg/scripts.pory"
	.string "Are you good?$"
# 69 "data/maps/Route6_Frlg/scripts.pory"

# 70 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_ElijahDefeat::
# 71 "data/maps/Route6_Frlg/scripts.pory"
	.string "You're too good!$"
# 72 "data/maps/Route6_Frlg/scripts.pory"

# 73 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_ElijahPostBattle::
# 74 "data/maps/Route6_Frlg/scripts.pory"
	.string "Are my POKéMON weak?\n"
# 75 "data/maps/Route6_Frlg/scripts.pory"
	.string "Or, am I just bad?\l"
# 76 "data/maps/Route6_Frlg/scripts.pory"
	.string "Which do you think?$"
# 77 "data/maps/Route6_Frlg/scripts.pory"

# 78 "data/maps/Route6_Frlg/scripts.pory"
Route6_Text_UndergroundPathSign::
# 79 "data/maps/Route6_Frlg/scripts.pory"
	.string "UNDERGROUND PATH\n"
# 80 "data/maps/Route6_Frlg/scripts.pory"
	.string "CERULEAN CITY - VERMILION CITY$"
