# 1 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 2 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Frlg_MapScripts::
# 3 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 5 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_EventScript_Rocket::
# 6 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_46, SixIsland_OutcastIsland_Text_RocketIntro, SixIsland_OutcastIsland_Text_RocketDefeat
# 7 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	msgbox SixIsland_OutcastIsland_Text_RocketPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	end
# 9 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 10 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_RocketIntro::
# 11 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "There're no rare POKéMON around\n"
# 12 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "these parts! Not a one!\p"
# 13 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "That burns me up, man.\n"
# 14 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I'll take it out on you!$"
# 15 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 16 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_RocketDefeat::
# 17 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "…Huh?$"
# 18 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 19 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_RocketPostBattle::
# 20 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "So listen, you haven't seen any\n"
# 21 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "rare POKéMON, have you?$"
# 22 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 23 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_TylorIntro::
# 24 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I'm having no luck at all.\n"
# 25 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "A battle'd be a change of pace!$"
# 26 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 27 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_TylorDefeat::
# 28 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Nope, no luck at all…$"
# 29 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 30 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_TylorPostBattle::
# 31 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I can't very well go home without\n"
# 32 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "catching something, though.$"
# 33 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 34 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_MymoIntro::
# 35 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Gasp… Gasp…\p"
# 36 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I swam here from SIX ISLE PORT\n"
# 37 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "in one go.$"
# 38 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 39 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_MymoDefeat::
# 40 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Gasp…\n"
# 41 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Gasp…$"
# 42 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 43 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_MymoPostBattle::
# 44 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I'm only at the halfway point…\n"
# 45 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I'm beat…$"
# 46 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 47 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_NicoleIntro::
# 48 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "It's not so easy sending POKéMON\n"
# 49 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "out while swimming, you know?$"
# 50 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 51 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_NicoleDefeat::
# 52 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I didn't lose to you at swimming.\n"
# 53 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "This doesn't bother me.$"
# 54 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 55 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_NicolePostBattle::
# 56 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Are you headed for the island up\n"
# 57 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "past here?\p"
# 58 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "I didn't see anything interesting\n"
# 59 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "there.$"
# 60 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 61 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_AvaIntro::
# 62 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "AVA: Let's have a two-on-two\n"
# 63 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "marine battle!$"
# 64 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 65 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_AvaDefeat::
# 66 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "AVA: Oh, you're amazing!\n"
# 67 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Even better, you're on your own!$"
# 68 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 69 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_AvaPostBattle::
# 70 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "AVA: You know, I do prefer the\n"
# 71 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "sea over any pool.$"
# 72 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 73 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
# 74 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "AVA: You're challenging us to\n"
# 75 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "a battle?\p"
# 76 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "You'll need at least two POKéMON\n"
# 77 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "if you want to do that.$"
# 78 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 79 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_GebIntro::
# 80 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "GEB: Big Sister, help!\n"
# 81 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "Please battle with me!$"
# 82 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 83 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_GebDefeat::
# 84 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "GEB: Wow, Big Sister, this person's\n"
# 85 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "really good!$"
# 86 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 87 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_GebPostBattle::
# 88 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "GEB: I'm hanging onto my sister\n"
# 89 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "because I can't touch the bottom.$"
# 90 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"

# 91 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
SixIsland_OutcastIsland_Text_GebNotEnoughMons::
# 92 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "GEB: Please battle against me and\n"
# 93 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "my sister!\p"
# 94 "data/maps/SixIsland_OutcastIsland_Frlg/scripts.pory"
	.string "…Oh, you don't have two POKéMON?$"
