# 1 "data/maps/Route14_Frlg/scripts.pory"

# 2 "data/maps/Route14_Frlg/scripts.pory"
Route14_Frlg_MapScripts::
# 3 "data/maps/Route14_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route14_Frlg/scripts.pory"

# 5 "data/maps/Route14_Frlg/scripts.pory"
Route14_EventScript_RouteSign::
# 6 "data/maps/Route14_Frlg/scripts.pory"
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/Route14_Frlg/scripts.pory"
	end
# 8 "data/maps/Route14_Frlg/scripts.pory"

# 9 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_CarterIntro::
# 10 "data/maps/Route14_Frlg/scripts.pory"
	.string "You need to use TMs to teach good\n"
# 11 "data/maps/Route14_Frlg/scripts.pory"
	.string "moves to POKéMON.$"
# 12 "data/maps/Route14_Frlg/scripts.pory"

# 13 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_CarterDefeat::
# 14 "data/maps/Route14_Frlg/scripts.pory"
	.string "Not good enough quite yet.$"
# 15 "data/maps/Route14_Frlg/scripts.pory"

# 16 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_CarterPostBattle::
# 17 "data/maps/Route14_Frlg/scripts.pory"
	.string "You have some HMs, right? POKéMON\n"
# 18 "data/maps/Route14_Frlg/scripts.pory"
	.string "can't forget those moves easily.$"
# 19 "data/maps/Route14_Frlg/scripts.pory"

# 20 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MitchIntro::
# 21 "data/maps/Route14_Frlg/scripts.pory"
	.string "My bird POKéMON should be ready\n"
# 22 "data/maps/Route14_Frlg/scripts.pory"
	.string "for battle.$"
# 23 "data/maps/Route14_Frlg/scripts.pory"

# 24 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MitchDefeat::
# 25 "data/maps/Route14_Frlg/scripts.pory"
	.string "Not ready yet!$"
# 26 "data/maps/Route14_Frlg/scripts.pory"

# 27 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MitchPostBattle::
# 28 "data/maps/Route14_Frlg/scripts.pory"
	.string "My bird POKéMON need to learn\n"
# 29 "data/maps/Route14_Frlg/scripts.pory"
	.string "better moves.$"
# 30 "data/maps/Route14_Frlg/scripts.pory"

# 31 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_BeckIntro::
# 32 "data/maps/Route14_Frlg/scripts.pory"
	.string "They have TMs on sale at the\n"
# 33 "data/maps/Route14_Frlg/scripts.pory"
	.string "CELADON DEPT. STORE.\p"
# 34 "data/maps/Route14_Frlg/scripts.pory"
	.string "TMs aren't really rare, but not\n"
# 35 "data/maps/Route14_Frlg/scripts.pory"
	.string "many people have HMs.$"
# 36 "data/maps/Route14_Frlg/scripts.pory"

# 37 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_BeckDefeat::
# 38 "data/maps/Route14_Frlg/scripts.pory"
	.string "Aww, bummer!$"
# 39 "data/maps/Route14_Frlg/scripts.pory"

# 40 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_BeckPostBattle::
# 41 "data/maps/Route14_Frlg/scripts.pory"
	.string "Try teaching POKéMON a move that's\n"
# 42 "data/maps/Route14_Frlg/scripts.pory"
	.string "the same type as it.\p"
# 43 "data/maps/Route14_Frlg/scripts.pory"
	.string "That apparently boosts the power\n"
# 44 "data/maps/Route14_Frlg/scripts.pory"
	.string "of the move.$"
# 45 "data/maps/Route14_Frlg/scripts.pory"

# 46 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MarlonIntro::
# 47 "data/maps/Route14_Frlg/scripts.pory"
	.string "Have you taught your bird POKéMON\n"
# 48 "data/maps/Route14_Frlg/scripts.pory"
	.string "how to FLY?\p"
# 49 "data/maps/Route14_Frlg/scripts.pory"
	.string "You'll be able to soar with it into\n"
# 50 "data/maps/Route14_Frlg/scripts.pory"
	.string "the sky!$"
# 51 "data/maps/Route14_Frlg/scripts.pory"

# 52 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MarlonDefeat::
# 53 "data/maps/Route14_Frlg/scripts.pory"
	.string "Shot down in flames!$"
# 54 "data/maps/Route14_Frlg/scripts.pory"

# 55 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MarlonPostBattle::
# 56 "data/maps/Route14_Frlg/scripts.pory"
	.string "Bird POKéMON are my one true love.\n"
# 57 "data/maps/Route14_Frlg/scripts.pory"
	.string "I don't want to raise anything else.$"
# 58 "data/maps/Route14_Frlg/scripts.pory"

# 59 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_DonaldIntro::
# 60 "data/maps/Route14_Frlg/scripts.pory"
	.string "Have you heard the legend of the\n"
# 61 "data/maps/Route14_Frlg/scripts.pory"
	.string "winged mirages?$"
# 62 "data/maps/Route14_Frlg/scripts.pory"

# 63 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_DonaldDefeat::
# 64 "data/maps/Route14_Frlg/scripts.pory"
	.string "Why?\n"
# 65 "data/maps/Route14_Frlg/scripts.pory"
	.string "Why'd I lose?$"
# 66 "data/maps/Route14_Frlg/scripts.pory"

# 67 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_DonaldPostBattle::
# 68 "data/maps/Route14_Frlg/scripts.pory"
	.string "Well, the winged mirages are the\n"
# 69 "data/maps/Route14_Frlg/scripts.pory"
	.string "legendary bird POKéMON.\p"
# 70 "data/maps/Route14_Frlg/scripts.pory"
	.string "There are three of them: ARTICUNO,\n"
# 71 "data/maps/Route14_Frlg/scripts.pory"
	.string "ZAPDOS, and MOLTRES.$"
# 72 "data/maps/Route14_Frlg/scripts.pory"

# 73 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_BennyIntro::
# 74 "data/maps/Route14_Frlg/scripts.pory"
	.string "I'm not into it, but okay.\n"
# 75 "data/maps/Route14_Frlg/scripts.pory"
	.string "Let's go!$"
# 76 "data/maps/Route14_Frlg/scripts.pory"

# 77 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_BennyDefeat::
# 78 "data/maps/Route14_Frlg/scripts.pory"
	.string "I knew it!$"
# 79 "data/maps/Route14_Frlg/scripts.pory"

# 80 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_BennyPostBattle::
# 81 "data/maps/Route14_Frlg/scripts.pory"
	.string "Winning, losing… It's insignificant\n"
# 82 "data/maps/Route14_Frlg/scripts.pory"
	.string "under this huge sky.$"
# 83 "data/maps/Route14_Frlg/scripts.pory"

# 84 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_LukasIntro::
# 85 "data/maps/Route14_Frlg/scripts.pory"
	.string "C'mon, c'mon.\n"
# 86 "data/maps/Route14_Frlg/scripts.pory"
	.string "Let's go, let's go, let's go!$"
# 87 "data/maps/Route14_Frlg/scripts.pory"

# 88 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_LukasDefeat::
# 89 "data/maps/Route14_Frlg/scripts.pory"
	.string "Arrg!\n"
# 90 "data/maps/Route14_Frlg/scripts.pory"
	.string "Lost! Get lost!$"
# 91 "data/maps/Route14_Frlg/scripts.pory"

# 92 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_LukasPostBattle::
# 93 "data/maps/Route14_Frlg/scripts.pory"
	.string "What, what, what?\n"
# 94 "data/maps/Route14_Frlg/scripts.pory"
	.string "What do you want still?$"
# 95 "data/maps/Route14_Frlg/scripts.pory"

# 96 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_IsaacIntro::
# 97 "data/maps/Route14_Frlg/scripts.pory"
	.string "I need to burn some time.\n"
# 98 "data/maps/Route14_Frlg/scripts.pory"
	.string "Shut up and battle.$"
# 99 "data/maps/Route14_Frlg/scripts.pory"

# 100 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_IsaacDefeat::
# 101 "data/maps/Route14_Frlg/scripts.pory"
	.string "What?\n"
# 102 "data/maps/Route14_Frlg/scripts.pory"
	.string "You!?$"
# 103 "data/maps/Route14_Frlg/scripts.pory"

# 104 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_IsaacPostBattle::
# 105 "data/maps/Route14_Frlg/scripts.pory"
	.string "Raising POKéMON is a drag, man.$"
# 106 "data/maps/Route14_Frlg/scripts.pory"

# 107 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_GeraldIntro::
# 108 "data/maps/Route14_Frlg/scripts.pory"
	.string "We ride out here because of the\n"
# 109 "data/maps/Route14_Frlg/scripts.pory"
	.string "wide-open spaces.$"
# 110 "data/maps/Route14_Frlg/scripts.pory"

# 111 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_GeraldDefeat::
# 112 "data/maps/Route14_Frlg/scripts.pory"
	.string "Wipeout!$"
# 113 "data/maps/Route14_Frlg/scripts.pory"

# 114 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_GeraldPostBattle::
# 115 "data/maps/Route14_Frlg/scripts.pory"
	.string "It's cool you made your POKéMON so\n"
# 116 "data/maps/Route14_Frlg/scripts.pory"
	.string "strong.\p"
# 117 "data/maps/Route14_Frlg/scripts.pory"
	.string "Might is right!\n"
# 118 "data/maps/Route14_Frlg/scripts.pory"
	.string "And you know it!$"
# 119 "data/maps/Route14_Frlg/scripts.pory"

# 120 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MalikIntro::
# 121 "data/maps/Route14_Frlg/scripts.pory"
	.string "POKéMON battle?\n"
# 122 "data/maps/Route14_Frlg/scripts.pory"
	.string "Cool! Rumble!$"
# 123 "data/maps/Route14_Frlg/scripts.pory"

# 124 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MalikDefeat::
# 125 "data/maps/Route14_Frlg/scripts.pory"
	.string "Blown away!$"
# 126 "data/maps/Route14_Frlg/scripts.pory"

# 127 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_MalikPostBattle::
# 128 "data/maps/Route14_Frlg/scripts.pory"
	.string "You know who'd win, you and me\n"
# 129 "data/maps/Route14_Frlg/scripts.pory"
	.string "one-on-one!$"
# 130 "data/maps/Route14_Frlg/scripts.pory"

# 131 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_RouteSign::
# 132 "data/maps/Route14_Frlg/scripts.pory"
	.string "ROUTE 14\n"
# 133 "data/maps/Route14_Frlg/scripts.pory"
	.string "West to FUCHSIA CITY$"
# 134 "data/maps/Route14_Frlg/scripts.pory"

# 135 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_KiriIntro::
# 136 "data/maps/Route14_Frlg/scripts.pory"
	.string "KIRI: JAN, let's try really,\n"
# 137 "data/maps/Route14_Frlg/scripts.pory"
	.string "really hard together.$"
# 138 "data/maps/Route14_Frlg/scripts.pory"

# 139 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_KiriDefeat::
# 140 "data/maps/Route14_Frlg/scripts.pory"
	.string "KIRI: Whimper…\n"
# 141 "data/maps/Route14_Frlg/scripts.pory"
	.string "We lost, didn't we?$"
# 142 "data/maps/Route14_Frlg/scripts.pory"

# 143 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_KiriPostBattle::
# 144 "data/maps/Route14_Frlg/scripts.pory"
	.string "KIRI: Did we lose because of me?$"
# 145 "data/maps/Route14_Frlg/scripts.pory"

# 146 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_KiriNotEnoughMons::
# 147 "data/maps/Route14_Frlg/scripts.pory"
	.string "KIRI: We can battle if you have\n"
# 148 "data/maps/Route14_Frlg/scripts.pory"
	.string "two POKéMON.$"
# 149 "data/maps/Route14_Frlg/scripts.pory"

# 150 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_JanIntro::
# 151 "data/maps/Route14_Frlg/scripts.pory"
	.string "JAN: KIRI, here we go!\n"
# 152 "data/maps/Route14_Frlg/scripts.pory"
	.string "We have to try hard!$"
# 153 "data/maps/Route14_Frlg/scripts.pory"

# 154 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_JanDefeat::
# 155 "data/maps/Route14_Frlg/scripts.pory"
	.string "JAN: Eeeeh!\n"
# 156 "data/maps/Route14_Frlg/scripts.pory"
	.string "No fair!$"
# 157 "data/maps/Route14_Frlg/scripts.pory"

# 158 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_JanPostBattle::
# 159 "data/maps/Route14_Frlg/scripts.pory"
	.string "JAN: KIRI, don't cry!\n"
# 160 "data/maps/Route14_Frlg/scripts.pory"
	.string "We'll just try harder next time.$"
# 161 "data/maps/Route14_Frlg/scripts.pory"

# 162 "data/maps/Route14_Frlg/scripts.pory"
Route14_Text_JanNotEnoughMons::
# 163 "data/maps/Route14_Frlg/scripts.pory"
	.string "JAN: You want to battle?\n"
# 164 "data/maps/Route14_Frlg/scripts.pory"
	.string "You don't have enough POKéMON.$"
