# 1 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
SafariZone_Center_RestHouse_Frlg_MapScripts::
# 3 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
SafariZone_Center_RestHouse_EventScript_Sara::
# 6 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
# 7 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	end
# 8 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"

# 9 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
SafariZone_Center_RestHouse_EventScript_Scientist::
# 10 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
# 11 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	end
# 12 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"

# 13 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
SafariZone_Center_Text_WhereDidErikGo::
# 14 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	.string "SARA: Where did my boyfriend,\n"
# 15 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	.string "ERIK, go?$"
# 16 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
SafariZone_Center_Text_CatchingMonsAsGifts::
# 18 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	.string "I'm catching POKéMON to take home\n"
# 19 "data/maps/SafariZone_Center_RestHouse_Frlg/scripts.pory"
	.string "as gifts.$"
