# 1 "data/maps/FourIsland_House1_Frlg/scripts.pory"

# 2 "data/maps/FourIsland_House1_Frlg/scripts.pory"
FourIsland_House1_Frlg_MapScripts::
# 3 "data/maps/FourIsland_House1_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/FourIsland_House1_Frlg/scripts.pory"

# 5 "data/maps/FourIsland_House1_Frlg/scripts.pory"
FourIsland_House1_EventScript_FatMan::
# 6 "data/maps/FourIsland_House1_Frlg/scripts.pory"
	msgbox FourIsland_House1_Text_YoureAwfullyHeavy, MSGBOX_NPC
# 7 "data/maps/FourIsland_House1_Frlg/scripts.pory"
	end
# 8 "data/maps/FourIsland_House1_Frlg/scripts.pory"

# 9 "data/maps/FourIsland_House1_Frlg/scripts.pory"
FourIsland_House1_Text_YoureAwfullyHeavy::
# 10 "data/maps/FourIsland_House1_Frlg/scripts.pory"
	.string "There! Boing!\n"
# 11 "data/maps/FourIsland_House1_Frlg/scripts.pory"
	.string "You're awfully heavy!$"
