# 1 "data/maps/Route5_Frlg/scripts.pory"

# 2 "data/maps/Route5_Frlg/scripts.pory"
Route5_Frlg_MapScripts::
# 3 "data/maps/Route5_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route5_Frlg/scripts.pory"

# 5 "data/maps/Route5_Frlg/scripts.pory"
Route5_EventScript_UndergroundPathSign::
# 6 "data/maps/Route5_Frlg/scripts.pory"
	msgbox Route5_Text_UndergroundPathSign, MSGBOX_SIGN
# 7 "data/maps/Route5_Frlg/scripts.pory"
	end
# 8 "data/maps/Route5_Frlg/scripts.pory"

# 9 "data/maps/Route5_Frlg/scripts.pory"
Route5_Text_UndergroundPathSign::
# 10 "data/maps/Route5_Frlg/scripts.pory"
	.string "UNDERGROUND PATH\n"
# 11 "data/maps/Route5_Frlg/scripts.pory"
	.string "CERULEAN CITY - VERMILION CITY$"
