# 1 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 2 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_Frlg_MapScripts::
# 3 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 5 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_EventScript_Receptionist::
# 6 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	msgbox CeladonCity_Hotel_Text_ThisHotelIsForPeople, MSGBOX_NPC
# 7 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	end
# 8 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 9 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_EventScript_Beauty::
# 10 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	msgbox CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend, MSGBOX_NPC
# 11 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	end
# 12 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 13 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_EventScript_BeautyBoyfriend::
# 14 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	msgbox CeladonCity_Hotel_Text_WhyDidSheBringBrother, MSGBOX_NPC
# 15 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	end
# 16 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 17 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_EventScript_BeautyBrother::
# 18 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	msgbox CeladonCity_Hotel_Text_SisBroughtMeOnVacation, MSGBOX_NPC
# 19 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	end
# 20 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 21 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_Text_ThisHotelIsForPeople::
# 22 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "POKéMON?\n"
# 23 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "No, this is a hotel for people.\p"
# 24 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "We're full up, unfortunately.$"
# 25 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 26 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
# 27 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "I'm on vacation with my brother and\n"
# 28 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "boyfriend.\p"
# 29 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "CELADON is such a pretty city!$"
# 30 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 31 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_Text_WhyDidSheBringBrother::
# 32 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "Why?\n"
# 33 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "Why did she bring her brother?$"
# 34 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"

# 35 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
# 36 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "Yippee! I'm on vacation!\n"
# 37 "data/maps/CeladonCity_Hotel_Frlg/scripts.pory"
	.string "My sis brought me along! Awesome!$"
