# 1 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_Frlg_MapScripts::
# 3 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_EventScript_RestHouseSign::
# 6 "data/maps/SafariZone_East_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_RestHouse, MSGBOX_SIGN
# 7 "data/maps/SafariZone_East_Frlg/scripts.pory"
	end
# 8 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 9 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_EventScript_TrainerTips::
# 10 "data/maps/SafariZone_East_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk, MSGBOX_SIGN
# 11 "data/maps/SafariZone_East_Frlg/scripts.pory"
	end
# 12 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 13 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_EventScript_AreaSign::
# 14 "data/maps/SafariZone_East_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_AreaSign, MSGBOX_SIGN
# 15 "data/maps/SafariZone_East_Frlg/scripts.pory"
	end
# 16 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_Text_RestHouse::
# 18 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "REST HOUSE$"
# 19 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 20 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
# 21 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 22 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "The remaining time declines only\n"
# 23 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "while you walk.$"
# 24 "data/maps/SafariZone_East_Frlg/scripts.pory"

# 25 "data/maps/SafariZone_East_Frlg/scripts.pory"
SafariZone_East_Text_AreaSign::
# 26 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "AREA 1\n"
# 27 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "WEST: CENTER AREA$"
