# 1 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"

# 2 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
DiglettsCave_NorthEntrance_Frlg_MapScripts::
# 3 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"

# 5 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
DiglettsCave_NorthEntrance_EventScript_Hiker::
# 6 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	msgbox DiglettsCave_NorthEntrance_RockTunnelPitchBlack, MSGBOX_NPC
# 7 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	end
# 8 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"

# 9 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
DiglettsCave_NorthEntrance_RockTunnelPitchBlack::
# 10 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	.string "I went inside ROCK TUNNEL, but it's\n"
# 11 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	.string "pitch-black and scary in there.\p"
# 12 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	.string "If I could get a POKéMON to use\n"
# 13 "data/maps/DiglettsCave_NorthEntrance_Frlg/scripts.pory"
	.string "FLASH and light it up…$"
