# 1 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"

# 2 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
ThreeIsland_House4_Frlg_MapScripts::
# 3 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"

# 5 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
ThreeIsland_House4_EventScript_BaldingMan::
# 6 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
# 7 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	end
# 8 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"

# 9 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
ThreeIsland_House4_EventScript_LittleBoy::
# 10 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
# 11 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	end
# 12 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"

# 13 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
ThreeIsland_House4_Text_GhostsInBerryForest::
# 14 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.string "You must never, ever go out to\n"
# 15 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.string "the BERRY FOREST alone.\p"
# 16 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.string "Why?\n"
# 17 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.string "There are ghosts there.$"
# 18 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"

# 19 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
ThreeIsland_House4_Text_PapaKeepsLyingToMe::
# 20 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.string "Papa keeps lying to me, and won't\n"
# 21 "data/maps/ThreeIsland_House4_Frlg/scripts.pory"
	.string "let me go out and play!$"
