# 1 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"

# 2 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
CeruleanCity_PokemonCenter_2F_Frlg_MapScripts::
# 3 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame_Frlg
# 4 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp_Frlg
# 5 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad_Frlg
# 6 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition_Frlg
# 7 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	.byte 0
# 8 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"

# 9 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
@ The below 3 are unused and leftover from RS
# 10 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
CeruleanCity_PokemonCenter_2F_EventScript_Colosseum::
# 11 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	call CableClub_EventScript_Colosseum_Frlg
# 12 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	end
# 13 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"

# 14 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
CeruleanCity_PokemonCenter_2F_EventScript_TradeCenter::
# 15 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	call CableClub_EventScript_TradeCenter_Frlg
# 16 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	end
# 17 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"

# 18 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
CeruleanCity_PokemonCenter_2F_EventScript_RecordCorner::
# 19 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	call CableClub_EventScript_RecordCorner_Frlg
# 20 "data/maps/CeruleanCity_PokemonCenter_2F_Frlg/scripts.pory"
	end
