# 1 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 2 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_Frlg_MapScripts::
# 3 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 5 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_Man::
# 6 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
# 7 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 8 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 9 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_OldMan::
# 10 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
# 11 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 12 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 13 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_Scientist::
# 14 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
# 15 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 16 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 17 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_LittleGirl::
# 18 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
# 19 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 20 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 21 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_BaldingMan::
# 22 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
# 23 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 24 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 25 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_SpaceShuttle::
# 26 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
# 27 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 28 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 29 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_MoonStone::
# 30 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
# 31 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 32 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 33 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossTeach::
# 34 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "The secrets of space…\n"
# 35 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "The mysteries of earth…\p"
# 36 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "There are so many things about\n"
# 37 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "which we know so little.\p"
# 38 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "But that should spur us to study\n"
# 39 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "harder, not toss in the towel.\p"
# 40 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "The only thing you should toss…\p"
# 41 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Well, how about SEISMIC TOSS?\n"
# 42 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Should I teach that to a POKéMON?$"
# 43 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 44 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossDeclined::
# 45 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Is that so?\n"
# 46 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I'm sure you'll be back for it.$"
# 47 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 48 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossWhichMon::
# 49 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Which POKéMON wants to learn\n"
# 50 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "SEISMIC TOSS?$"
# 51 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 52 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossTaught::
# 53 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I hope you won't toss in the towel.\n"
# 54 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Keep it up.$"
# 55 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 56 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
# 57 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "MOON STONE, huh?\p"
# 58 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "What's so special about it?\n"
# 59 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Looks like an ordinary rock to me.$"
# 60 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 61 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
# 62 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "July 20, 1969!\p"
# 63 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Humankind first set foot on the\n"
# 64 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "moon that day.\p"
# 65 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I bought a color TV just so I\n"
# 66 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "could watch that news.$"
# 67 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 68 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
# 69 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "This month, we're running a space\n"
# 70 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "exhibit.$"
# 71 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 72 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
# 73 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I want a PIKACHU!\n"
# 74 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "It's so cute!\p"
# 75 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I asked my daddy to catch me one!$"
# 76 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 77 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_PikachuSoonIPromise::
# 78 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Yeah, a PIKACHU soon, I promise!$"
# 79 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 80 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_SpaceShuttle::
# 81 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Space Shuttle$"
# 82 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 83 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
# 84 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "A meteorite that fell on MT. MOON.\n"
# 85 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "It is thought to be a MOON STONE.$"
