# 1 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
SSAnne_2F_Room3_Frlg_MapScripts::
# 3 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
SSAnne_2F_Room3_EventScript_Gentleman::
# 6 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
# 7 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	end
# 8 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"

# 9 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
SSAnne_2F_Room3_EventScript_OldMan::
# 10 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
# 11 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	end
# 12 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"

# 13 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
# 14 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "Ah, yes, I have seen some POKéMON\n"
# 15 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "ferry people across the water!$"
# 16 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"

# 17 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
# 18 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "Small trees can be chopped down\n"
# 19 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "using the move CUT.\p"
# 20 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "But remember this!\n"
# 21 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "CUT is an HM technique.\p"
# 22 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "Once learned, it is not so easily\n"
# 23 "data/maps/SSAnne_2F_Room3_Frlg/scripts.pory"
	.string "discarded.$"
