# 1 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 2 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Frlg_MapScripts::
# 3 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 5 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_EventScript_Paula::
# 6 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_PAULA, PokemonTower_4F_Text_PaulaIntro, PokemonTower_4F_Text_PaulaDefeat
# 7 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	msgbox PokemonTower_4F_Text_PaulaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	end
# 9 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 10 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_EventScript_Laurel::
# 11 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_LAUREL, PokemonTower_4F_Text_LaurelIntro, PokemonTower_4F_Text_LaurelDefeat
# 12 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	msgbox PokemonTower_4F_Text_LaurelPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	end
# 14 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 15 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_EventScript_Jody::
# 16 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_JODY, PokemonTower_4F_Text_JodyIntro, PokemonTower_4F_Text_JodyDefeat
# 17 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	msgbox PokemonTower_4F_Text_JodyPostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	end
# 19 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 20 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_PaulaIntro::
# 21 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Ghost! No!\n"
# 22 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Kwaaah!$"
# 23 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 24 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_PaulaDefeat::
# 25 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Where is the ghost?$"
# 26 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 27 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_PaulaPostBattle::
# 28 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "I must have been dreaming…$"
# 29 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 30 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_LaurelIntro::
# 31 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Be cursed with me!\n"
# 32 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Kwaaah!$"
# 33 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 34 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_LaurelDefeat::
# 35 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "What!$"
# 36 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 37 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_LaurelPostBattle::
# 38 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "We can't determine the identity of\n"
# 39 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "the ghosts…$"
# 40 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 41 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_JodyIntro::
# 42 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Huhuhu…\n"
# 43 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Beat me not!$"
# 44 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 45 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_JodyDefeat::
# 46 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Huh?\n"
# 47 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "Who? What?$"
# 48 "data/maps/PokemonTower_4F_Frlg/scripts.pory"

# 49 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
PokemonTower_4F_Text_JodyPostBattle::
# 50 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "May the departed POKéMON rest in\n"
# 51 "data/maps/PokemonTower_4F_Frlg/scripts.pory"
	.string "peace…$"
