# 1 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
SSAnne_1F_Room1_Frlg_MapScripts::
# 3 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
SSAnne_1F_Room1_EventScript_Gentleman::
# 6 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	msgbox SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent, MSGBOX_NPC
# 7 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	end
# 8 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"

# 9 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent::
# 10 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	.string "Ssh…!\n"
# 11 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	.string "I'm a GLOBAL POLICE agent.\p"
# 12 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	.string "I'm on the trail of TEAM ROCKET.\n"
# 13 "data/maps/SSAnne_1F_Room1_Frlg/scripts.pory"
	.string "They're up to nothing good!$"
