# 1 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"

# 2 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
UndergroundPath_SouthEntrance_Frlg_MapScripts::
# 3 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"

# 5 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
UndergroundPath_SouthEntrance_EventScript_Woman::
# 6 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	msgbox UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness, MSGBOX_NPC
# 7 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	end
# 8 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"

# 9 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness::
# 10 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	.string "People often lose things in the\n"
# 11 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	.string "darkness of the UNDERGROUND PATH.$"
