# 1 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 2 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
@ Handled by data/scripts/day_care.inc
# 3 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 4 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Frlg_MapScripts::
# 5 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.byte 0
# 6 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 7 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_WantMeToRaiseMon::
# 8 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "I run the DAY-CARE service.\p"
# 9 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Would you like me to raise one of\n"
# 10 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "your POKéMON?$"
# 11 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 12 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_ComeAgain::
# 13 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Come again.$"
# 14 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 15 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
# 16 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Which POKéMON should I raise?$"
# 17 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 18 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
# 19 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Fine.\n"
# 20 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Come anytime you like.$"
# 21 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 22 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
# 23 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Fine, I'll look after your\n"
# 24 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "{STR_VAR_1} for a while.$"
# 25 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 26 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
# 27 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Come see me in a while.$"
# 28 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 29 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
# 30 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "You're back already?\p"
# 31 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Your {STR_VAR_1} needs to spend\n"
# 32 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "some more time with me.$"
# 33 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 34 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
# 35 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "You owe me ¥{STR_VAR_2} for the return\n"
# 36 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "of this POKéMON.$"
# 37 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 38 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_ThankYouHeresMon::
# 39 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Thank you!\n"
# 40 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Here's your POKéMON.$"
# 41 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 42 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_PlayerGotMonBack::
# 43 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "{PLAYER} got {STR_VAR_1} back\n"
# 44 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "from the DAY-CARE MAN.$"
# 45 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 46 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
# 47 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Oh? You only have one POKéMON\n"
# 48 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "with you.$"
# 49 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 50 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
# 51 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "If you leave me that POKéMON,\n"
# 52 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "what will you battle with?$"
# 53 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 54 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
# 55 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Your {STR_VAR_1} has grown a lot.\n"
# 56 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Yes, quite a lot, I'd say.\p"
# 57 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Let me see…\n"
# 58 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "By level, it's grown by {STR_VAR_2}.\p"
# 59 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "Aren't I great?$"
# 60 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 61 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
# 62 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "You can't take this POKéMON back\n"
# 63 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "if you've got no room for it.$"
# 64 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 65 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
# 66 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "You don't have enough money.$"
# 67 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 68 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
# 69 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "きみの\n"
# 70 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "みてみるかね？$"
# 71 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"

# 72 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
# 73 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "わるいけど　ひでんのわざを　もった\n"
# 74 "data/maps/Route5_PokemonDayCare_Frlg/scripts.pory"
	.string "ポケモンは　あずかれないなぁ$"
