# 1 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"

# 2 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
OneIsland_TreasureBeach_Frlg_MapScripts::
# 3 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"

# 5 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
OneIsland_TreasureBeach_EventScript_Boy::
# 6 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
# 7 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	end
# 8 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"

# 9 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
OneIsland_TreasureBeach_Text_AmaraIntro::
# 10 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "Lying back, rocked by the waves…\n"
# 11 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "It's exquisite.$"
# 12 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"

# 13 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
OneIsland_TreasureBeach_Text_AmaraDefeat::
# 14 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "I lost…\n"
# 15 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "It feels awful.$"
# 16 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"

# 17 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
OneIsland_TreasureBeach_Text_AmaraPostBattle::
# 18 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "The sea is pleasantly warm in these\n"
# 19 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "parts.$"
# 20 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"

# 21 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
# 22 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "Good things get washed up by the\n"
# 23 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "ocean current onto this beach.\p"
# 24 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "That's why I often come here for\n"
# 25 "data/maps/OneIsland_TreasureBeach_Frlg/scripts.pory"
	.string "some beachcombing.$"
