# 1 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 2 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Frlg_MapScripts::
# 3 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 5 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_CounterTutor::
# 6 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	goto EventScript_CounterTutor
# 7 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 8 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 9 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
# 10 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
# 11 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 12 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 13 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
# 14 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
# 15 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 16 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 17 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
# 18 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
# 19 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 20 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 21 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
# 22 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
# 23 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 24 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 25 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
# 26 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
# 27 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 28 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 29 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV1::
# 30 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
# 31 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 32 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 33 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV2::
# 34 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
# 35 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 36 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 37 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV3::
# 38 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
# 39 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 40 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 41 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV4::
# 42 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
# 43 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 44 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 45 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
# 46 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
# 47 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 48 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 49 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_Poster::
# 50 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
# 51 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	end
# 52 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 53 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
# 54 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Captured POKéMON are registered\n"
# 55 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "with an ID No. and the OT.\p"
# 56 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "OT stands for “Original TRAINER” -\n"
# 57 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "the TRAINER that caught it first.$"
# 58 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 59 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
# 60 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "All right!\p"
# 61 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "My buddy's going to trade me his\n"
# 62 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "KANGASKHAN for my HAUNTER!$"
# 63 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 64 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
# 65 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Come on, HAUNTER!\p"
# 66 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "I love HAUNTER!\n"
# 67 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "I collect them!\p"
# 68 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Huh?\p"
# 69 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "HAUNTER turned into a different\n"
# 70 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "POKéMON while being traded!$"
# 71 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 72 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
# 73 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "You can identify POKéMON you get\n"
# 74 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "in trades by their ID Numbers.$"
# 75 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 76 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
# 77 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "It's a Super NES.$"
# 78 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 79 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_AnRPG::
# 80 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "An RPG!\n"
# 81 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "There's no time for that!$"
# 82 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 83 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_SportsGame::
# 84 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "A sports game!\n"
# 85 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Dad'll like that!$"
# 86 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 87 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
# 88 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "A puzzle game!\n"
# 89 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Looks addictive!$"
# 90 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 91 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_FightingGame::
# 92 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "A fighting game!\n"
# 93 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Looks tough!$"
# 94 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 95 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_TVGameShop::
# 96 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "3F: TV GAME SHOP$"
# 97 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 98 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
# 99 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Red and Green!\n"
# 100 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Both are POKéMON!$"
# 101 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 102 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
Text_CounterTeach::
# 103 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Oh, hi!\n"
# 104 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "I finally finished POKéMON.\p"
# 105 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Not done yet? How about I teach\n"
# 106 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "you a good move?\p"
# 107 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "The move I have in mind is\n"
# 108 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "COUNTER.\p"
# 109 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Not like the one I'm leaning on,\n"
# 110 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "mind you!$"
# 111 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 112 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
Text_CounterDeclined::
# 113 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "You're not interested? Come see\n"
# 114 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "me if you change your mind.$"
# 115 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 116 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
Text_CounterWhichMon::
# 117 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Which POKéMON should I teach\n"
# 118 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "COUNTER to?$"
# 119 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"

# 120 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
Text_CounterTaught::
# 121 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "Are you using that COUNTER move\n"
# 122 "data/maps/CeladonCity_DepartmentStore_3F_Frlg/scripts.pory"
	.string "I taught your POKéMON?$"
