# 1 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
SSAnne_3F_Corridor_Frlg_MapScripts::
# 3 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
SSAnne_3F_Corridor_EventScript_Sailor::
# 6 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	msgbox SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons, MSGBOX_NPC
# 7 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	end
# 8 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"

# 9 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons::
# 10 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	.string "Our CAPTAIN is a sword master.\n"
# 11 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	.string "He's awesome at using CUT.\p"
# 12 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	.string "They say he even teaches CUT\n"
# 13 "data/maps/SSAnne_3F_Corridor_Frlg/scripts.pory"
	.string "to POKéMON!$"
