# 1 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"

# 2 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
DiglettsCave_SouthEntrance_Frlg_MapScripts::
# 3 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"

# 5 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
DiglettsCave_SouthEntrance_EventScript_OldMan::
# 6 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	msgbox DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel, MSGBOX_NPC
# 7 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	end
# 8 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"

# 9 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
# 10 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	.string "Well, isn't this a surprise!\n"
# 11 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	.string "DIGLETT dug this long tunnel!\p"
# 12 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	.string "It goes right to VIRIDIAN CITY,\n"
# 13 "data/maps/DiglettsCave_SouthEntrance_Frlg/scripts.pory"
	.string "they tell me.$"
