# 1 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Frlg_MapScripts::
# 3 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_EventScript_Barny::
# 6 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	trainerbattle_single TRAINER_FISHERMAN_BARNY, SSAnne_B1F_Room1_Text_BarnyIntro, SSAnne_B1F_Room1_Text_BarnyDefeat
# 7 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	msgbox SSAnne_B1F_Room1_Text_BarnyPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	end
# 9 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 10 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_EventScript_Phillip::
# 11 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	trainerbattle_single TRAINER_SAILOR_PHILLIP, SSAnne_B1F_Room1_Text_PhillipIntro, SSAnne_B1F_Room1_Text_PhillipDefeat
# 12 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	msgbox SSAnne_B1F_Room1_Text_PhillipPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	end
# 14 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 15 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Text_PhillipIntro::
# 16 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "Matey, you're walking the plank if\n"
# 17 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "you lose!$"
# 18 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 19 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Text_PhillipDefeat::
# 20 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "Argh!\n"
# 21 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "Beaten by a kid!$"
# 22 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 23 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Text_PhillipPostBattle::
# 24 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "When we're out at sea, jellyfish\n"
# 25 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "POKéMON sometimes drift by.$"
# 26 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 27 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Text_BarnyIntro::
# 28 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "Hello, stranger!\p"
# 29 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "I can't tell if you're from the seas\n"
# 30 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "or mountains, but stop and chat.\p"
# 31 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "All my POKéMON are from the sea.$"
# 32 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 33 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Text_BarnyDefeat::
# 34 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "Darn!\n"
# 35 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "I let that one get away!$"
# 36 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"

# 37 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
SSAnne_B1F_Room1_Text_BarnyPostBattle::
# 38 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "I was going to make you my\n"
# 39 "data/maps/SSAnne_B1F_Room1_Frlg/scripts.pory"
	.string "assistant, too!$"
