# 1 "data/maps/Route10_Frlg/scripts.pory"

# 2 "data/maps/Route10_Frlg/scripts.pory"
Route10_Frlg_MapScripts::
# 3 "data/maps/Route10_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route10_Frlg/scripts.pory"

# 5 "data/maps/Route10_Frlg/scripts.pory"
Route10_EventScript_Unused::
# 6 "data/maps/Route10_Frlg/scripts.pory"
	end
# 7 "data/maps/Route10_Frlg/scripts.pory"

# 8 "data/maps/Route10_Frlg/scripts.pory"
Route10_EventScript_NorthRockTunnelSign::
# 9 "data/maps/Route10_Frlg/scripts.pory"
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
# 10 "data/maps/Route10_Frlg/scripts.pory"
	end
# 11 "data/maps/Route10_Frlg/scripts.pory"

# 12 "data/maps/Route10_Frlg/scripts.pory"
Route10_EventScript_SouthRockTunnelSign::
# 13 "data/maps/Route10_Frlg/scripts.pory"
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
# 14 "data/maps/Route10_Frlg/scripts.pory"
	end
# 15 "data/maps/Route10_Frlg/scripts.pory"

# 16 "data/maps/Route10_Frlg/scripts.pory"
Route10_EventScript_PowerPlantSign::
# 17 "data/maps/Route10_Frlg/scripts.pory"
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
# 18 "data/maps/Route10_Frlg/scripts.pory"
	end
# 19 "data/maps/Route10_Frlg/scripts.pory"

# 20 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_MarkIntro::
# 21 "data/maps/Route10_Frlg/scripts.pory"
	.string "Wow, you came all the way here?\n"
# 22 "data/maps/Route10_Frlg/scripts.pory"
	.string "Maybe you're a POKéMANIAC, too?\l"
# 23 "data/maps/Route10_Frlg/scripts.pory"
	.string "Want to see my collection?$"
# 24 "data/maps/Route10_Frlg/scripts.pory"

# 25 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_MarkDefeat::
# 26 "data/maps/Route10_Frlg/scripts.pory"
	.string "Humph.\n"
# 27 "data/maps/Route10_Frlg/scripts.pory"
	.string "I'm not angry!$"
# 28 "data/maps/Route10_Frlg/scripts.pory"

# 29 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_MarkPostBattle::
# 30 "data/maps/Route10_Frlg/scripts.pory"
	.string "I have more rare POKéMON at home!$"
# 31 "data/maps/Route10_Frlg/scripts.pory"

# 32 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_ClarkIntro::
# 33 "data/maps/Route10_Frlg/scripts.pory"
	.string "Ha-hahah-ah-ha!$"
# 34 "data/maps/Route10_Frlg/scripts.pory"

# 35 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_ClarkDefeat::
# 36 "data/maps/Route10_Frlg/scripts.pory"
	.string "Ha-haha!\n"
# 37 "data/maps/Route10_Frlg/scripts.pory"
	.string "Not laughing!\l"
# 38 "data/maps/Route10_Frlg/scripts.pory"
	.string "Ha-hay fever! Haha-ha-choo!$"
# 39 "data/maps/Route10_Frlg/scripts.pory"

# 40 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_ClarkPostBattle::
# 41 "data/maps/Route10_Frlg/scripts.pory"
	.string "Haha-ha-choo!\n"
# 42 "data/maps/Route10_Frlg/scripts.pory"
	.string "Ha-choo!\l"
# 43 "data/maps/Route10_Frlg/scripts.pory"
	.string "Snort! Snivel!$"
# 44 "data/maps/Route10_Frlg/scripts.pory"

# 45 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_HermanIntro::
# 46 "data/maps/Route10_Frlg/scripts.pory"
	.string "Hi, kid!\n"
# 47 "data/maps/Route10_Frlg/scripts.pory"
	.string "Want to see my POKéMON?$"
# 48 "data/maps/Route10_Frlg/scripts.pory"

# 49 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_HermanDefeat::
# 50 "data/maps/Route10_Frlg/scripts.pory"
	.string "Oh, no!\n"
# 51 "data/maps/Route10_Frlg/scripts.pory"
	.string "My POKéMON!$"
# 52 "data/maps/Route10_Frlg/scripts.pory"

# 53 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_HermanPostBattle::
# 54 "data/maps/Route10_Frlg/scripts.pory"
	.string "I don't like you.\n"
# 55 "data/maps/Route10_Frlg/scripts.pory"
	.string "I don't like anyone better than me!$"
# 56 "data/maps/Route10_Frlg/scripts.pory"

# 57 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_HeidiIntro::
# 58 "data/maps/Route10_Frlg/scripts.pory"
	.string "I've been out at a POKéMON GYM\n"
# 59 "data/maps/Route10_Frlg/scripts.pory"
	.string "a few times.\p"
# 60 "data/maps/Route10_Frlg/scripts.pory"
	.string "…But I always lose.$"
# 61 "data/maps/Route10_Frlg/scripts.pory"

# 62 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_HeidiDefeat::
# 63 "data/maps/Route10_Frlg/scripts.pory"
	.string "Ohh!\n"
# 64 "data/maps/Route10_Frlg/scripts.pory"
	.string "After all my training!$"
# 65 "data/maps/Route10_Frlg/scripts.pory"

# 66 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_HeidiPostBattle::
# 67 "data/maps/Route10_Frlg/scripts.pory"
	.string "I noticed some POKéMANIACS\n"
# 68 "data/maps/Route10_Frlg/scripts.pory"
	.string "prowling around.\p"
# 69 "data/maps/Route10_Frlg/scripts.pory"
	.string "Can you imagine? Them?\n"
# 70 "data/maps/Route10_Frlg/scripts.pory"
	.string "Up here in the mountains?$"
# 71 "data/maps/Route10_Frlg/scripts.pory"

# 72 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_TrentIntro::
# 73 "data/maps/Route10_Frlg/scripts.pory"
	.string "Ah!\n"
# 74 "data/maps/Route10_Frlg/scripts.pory"
	.string "This mountain air is delicious!$"
# 75 "data/maps/Route10_Frlg/scripts.pory"

# 76 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_TrentDefeat::
# 77 "data/maps/Route10_Frlg/scripts.pory"
	.string "That cleared my head!$"
# 78 "data/maps/Route10_Frlg/scripts.pory"

# 79 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_TrentPostBattle::
# 80 "data/maps/Route10_Frlg/scripts.pory"
	.string "I feel bloated on mountain air!$"
# 81 "data/maps/Route10_Frlg/scripts.pory"

# 82 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_CarolIntro::
# 83 "data/maps/Route10_Frlg/scripts.pory"
	.string "I'm feeling a bit faint.\n"
# 84 "data/maps/Route10_Frlg/scripts.pory"
	.string "I haven't hiked in some time.$"
# 85 "data/maps/Route10_Frlg/scripts.pory"

# 86 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_CarolDefeat::
# 87 "data/maps/Route10_Frlg/scripts.pory"
	.string "I'm too tired.\n"
# 88 "data/maps/Route10_Frlg/scripts.pory"
	.string "I wasn't up for it.$"
# 89 "data/maps/Route10_Frlg/scripts.pory"

# 90 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_CarolPostBattle::
# 91 "data/maps/Route10_Frlg/scripts.pory"
	.string "The POKéMON here in the mountains\n"
# 92 "data/maps/Route10_Frlg/scripts.pory"
	.string "are so chunky…\p"
# 93 "data/maps/Route10_Frlg/scripts.pory"
	.string "I wish there were pink POKéMON\n"
# 94 "data/maps/Route10_Frlg/scripts.pory"
	.string "with a floral pattern!$"
# 95 "data/maps/Route10_Frlg/scripts.pory"

# 96 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_RockTunnelDetourToLavender::
# 97 "data/maps/Route10_Frlg/scripts.pory"
	.string "ROCK TUNNEL\n"
# 98 "data/maps/Route10_Frlg/scripts.pory"
	.string "Detour to LAVENDER TOWN$"
# 99 "data/maps/Route10_Frlg/scripts.pory"

# 100 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_RockTunnel::
# 101 "data/maps/Route10_Frlg/scripts.pory"
	.string "ROCK TUNNEL$"
# 102 "data/maps/Route10_Frlg/scripts.pory"

# 103 "data/maps/Route10_Frlg/scripts.pory"
Route10_Text_PowerPlant::
# 104 "data/maps/Route10_Frlg/scripts.pory"
	.string "POWER PLANT$"
