# 1 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 2 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_Frlg_MapScripts::
# 3 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 5 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleABC::
# 6 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 7 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_ABC
# 8 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 9 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 10 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 11 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleGHI::
# 12 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 13 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_GHI
# 14 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 15 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 16 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 17 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleMNO::
# 18 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 19 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_MNO
# 20 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 21 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 22 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 23 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleTUV::
# 24 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 25 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_TUV
# 26 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 27 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 28 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 29 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleDEF::
# 30 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 31 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_DEF
# 32 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 33 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 34 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 35 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleJKL::
# 36 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 37 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_JKL
# 38 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 39 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 40 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 41 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BraillePQRS::
# 42 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 43 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_PQRS
# 44 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 45 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 46 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 47 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleWXYZ::
# 48 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 49 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_WXYZ
# 50 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 51 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 52 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 53 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BraillePeriod::
# 54 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 55 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_Period
# 56 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 57 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
# 58 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"

# 59 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
MtEmber_RubyPath_B4F_EventScript_BrailleComma::
# 60 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	lockall
# 61 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	braillemsgbox Braille_Text_Comma
# 62 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	releaseall
# 63 "data/maps/MtEmber_RubyPath_B4F_Frlg/scripts.pory"
	end
