# 1 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 2 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_Frlg_MapScripts::
# 3 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 5 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_EventScript_MetronomeTutor::
# 6 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	goto EventScript_MetronomeTutor
# 7 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	end
# 8 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 9 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_EventScript_Scientist::
# 10 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons, MSGBOX_NPC
# 11 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	end
# 12 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 13 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_EventScript_Computer::
# 14 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail, MSGBOX_SIGN
# 15 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	end
# 16 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 17 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_EventScript_AmberPipe::
# 18 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe, MSGBOX_SIGN
# 19 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	end
# 20 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 21 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
# 22 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "EEVEE can evolve into one of three\n"
# 23 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "kinds of POKéMON.$"
# 24 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 25 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
# 26 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "There's an e-mail message.\p"
# 27 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "… … …\p"
# 28 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "There are three legendary bird\n"
# 29 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "POKéMON.\p"
# 30 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "They are ARTICUNO, ZAPDOS, and\n"
# 31 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "MOLTRES.\p"
# 32 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "Their whereabouts are unknown.\p"
# 33 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "We plan to explore the cavern\n"
# 34 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "close to CERULEAN.\p"
# 35 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "From: POKéMON RESEARCH TEAM…$"
# 36 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"

# 37 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
# 38 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom_Frlg/scripts.pory"
	.string "An amber pipe!$"
