# 1 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 2 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
# 3 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 5 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker1::
# 6 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
# 7 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 8 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 9 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker2::
# 10 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
# 11 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 12 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 13 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker3::
# 14 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
# 15 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 16 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 17 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker4::
# 18 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
# 19 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 20 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 21 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
# 22 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "We nicknamed the WARDEN\n"
# 23 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "“SLOWPOKE.”\p"
# 24 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "You know, he has that vacant look\n"
# 25 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "like a SLOWPOKE.$"
# 26 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 27 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
# 28 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "WARDEN SLOWPOKE is very\n"
# 29 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "knowledgeable about POKéMON.\p"
# 30 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "He even has some fossils of rare,\n"
# 31 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "extinct POKéMON.$"
# 32 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 33 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
# 34 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "WARDEN SLOWPOKE came in, but\n"
# 35 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "I couldn't understand him.\p"
# 36 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "I think he's got a speech problem!$"
# 37 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 38 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
# 39 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "WARDEN SLOWPOKE is running a\n"
# 40 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "promotion campaign right now.\p"
# 41 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "Try to get to the farthest corner\n"
# 42 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "of the SAFARI ZONE.\p"
# 43 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "If you can make it, you'll win a\n"
# 44 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "very convenient prize.$"
