# 1 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"

# 2 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
Route12_NorthEntrance_1F_Frlg_MapScripts::
# 3 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"

# 5 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
Route12_NorthEntrance_1F_EventScript_Guard::
# 6 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
	msgbox Route12_NorthEntrance_1F_Text_LookoutSpotUpstairs, MSGBOX_NPC
# 7 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
	end
# 8 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"

# 9 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
Route12_NorthEntrance_1F_Text_LookoutSpotUpstairs::
# 10 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
	.string "There's a lookout spot upstairs.\n"
# 11 "data/maps/Route12_NorthEntrance_1F_Frlg/scripts.pory"
	.string "The view is magnificent.$"
