# 1 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Frlg_MapScripts::
# 3 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_EventScript_Lamar::
# 6 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	trainerbattle_single TRAINER_GENTLEMAN_LAMAR, SSAnne_2F_Room4_Text_LamarIntro, SSAnne_2F_Room4_Text_LamarDefeat
# 7 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room4_Text_LamarPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	end
# 9 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 10 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_EventScript_Dawn::
# 11 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	trainerbattle_single TRAINER_LASS_DAWN, SSAnne_2F_Room4_Text_DawnIntro, SSAnne_2F_Room4_Text_DawnDefeat
# 12 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room4_Text_DawnPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	end
# 14 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 15 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Text_LamarIntro::
# 16 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "Which do you find more worthy,\n"
# 17 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "a strong or a rare POKéMON?$"
# 18 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 19 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Text_LamarDefeat::
# 20 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "I must salute you!$"
# 21 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 22 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Text_LamarPostBattle::
# 23 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "Personally, I prefer strong and\n"
# 24 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "rare POKéMON.$"
# 25 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 26 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Text_DawnIntro::
# 27 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "I don't believe I saw you at the\n"
# 28 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "party?$"
# 29 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 30 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Text_DawnDefeat::
# 31 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "Take it easy!$"
# 32 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"

# 33 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
SSAnne_2F_Room4_Text_DawnPostBattle::
# 34 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "Oh, I adore your strong POKéMON!\n"
# 35 "data/maps/SSAnne_2F_Room4_Frlg/scripts.pory"
	.string "Oh, how I envy you for them!$"
