# 1 "data/maps/Route13_Frlg/scripts.pory"

# 2 "data/maps/Route13_Frlg/scripts.pory"
Route13_Frlg_MapScripts::
# 3 "data/maps/Route13_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route13_Frlg/scripts.pory"

# 5 "data/maps/Route13_Frlg/scripts.pory"
Route13_EventScript_TrainerTips1::
# 6 "data/maps/Route13_Frlg/scripts.pory"
	msgbox Route13_Text_LookToLeftOfThatPost, MSGBOX_SIGN
# 7 "data/maps/Route13_Frlg/scripts.pory"
	end
# 8 "data/maps/Route13_Frlg/scripts.pory"

# 9 "data/maps/Route13_Frlg/scripts.pory"
Route13_EventScript_TrainerTips2::
# 10 "data/maps/Route13_Frlg/scripts.pory"
	msgbox Route13_Text_SelectToSwitchItems, MSGBOX_SIGN
# 11 "data/maps/Route13_Frlg/scripts.pory"
	end
# 12 "data/maps/Route13_Frlg/scripts.pory"

# 13 "data/maps/Route13_Frlg/scripts.pory"
Route13_EventScript_RouteSign::
# 14 "data/maps/Route13_Frlg/scripts.pory"
	msgbox Route13_Text_RouteSign, MSGBOX_SIGN
# 15 "data/maps/Route13_Frlg/scripts.pory"
	end
# 16 "data/maps/Route13_Frlg/scripts.pory"

# 17 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SebastianIntro::
# 18 "data/maps/Route13_Frlg/scripts.pory"
	.string "My bird POKéMON want to battle\n"
# 19 "data/maps/Route13_Frlg/scripts.pory"
	.string "with you!$"
# 20 "data/maps/Route13_Frlg/scripts.pory"

# 21 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SebastianDefeat::
# 22 "data/maps/Route13_Frlg/scripts.pory"
	.string "My PIDGEY and PIDGEOTTO combo\n"
# 23 "data/maps/Route13_Frlg/scripts.pory"
	.string "lost?$"
# 24 "data/maps/Route13_Frlg/scripts.pory"

# 25 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SebastianPostBattle::
# 26 "data/maps/Route13_Frlg/scripts.pory"
	.string "My POKéMON look happy even though\n"
# 27 "data/maps/Route13_Frlg/scripts.pory"
	.string "they lost.$"
# 28 "data/maps/Route13_Frlg/scripts.pory"

# 29 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SusieIntro::
# 30 "data/maps/Route13_Frlg/scripts.pory"
	.string "I'm told I'm good for a kid.$"
# 31 "data/maps/Route13_Frlg/scripts.pory"

# 32 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SusieDefeat::
# 33 "data/maps/Route13_Frlg/scripts.pory"
	.string "Ohh!\n"
# 34 "data/maps/Route13_Frlg/scripts.pory"
	.string "I lost!$"
# 35 "data/maps/Route13_Frlg/scripts.pory"

# 36 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SusiePostBattle::
# 37 "data/maps/Route13_Frlg/scripts.pory"
	.string "I want to become a good TRAINER.\n"
# 38 "data/maps/Route13_Frlg/scripts.pory"
	.string "I'll train hard, just watch.$"
# 39 "data/maps/Route13_Frlg/scripts.pory"

# 40 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_ValerieIntro::
# 41 "data/maps/Route13_Frlg/scripts.pory"
	.string "Wow!\n"
# 42 "data/maps/Route13_Frlg/scripts.pory"
	.string "Your BADGES are too cool!$"
# 43 "data/maps/Route13_Frlg/scripts.pory"

# 44 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_ValerieDefeat::
# 45 "data/maps/Route13_Frlg/scripts.pory"
	.string "Not enough!$"
# 46 "data/maps/Route13_Frlg/scripts.pory"

# 47 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_ValeriePostBattle::
# 48 "data/maps/Route13_Frlg/scripts.pory"
	.string "You got those BADGES from GYM\n"
# 49 "data/maps/Route13_Frlg/scripts.pory"
	.string "LEADERS. I know!$"
# 50 "data/maps/Route13_Frlg/scripts.pory"

# 51 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_GwenIntro::
# 52 "data/maps/Route13_Frlg/scripts.pory"
	.string "My cute POKéMON wish to make your\n"
# 53 "data/maps/Route13_Frlg/scripts.pory"
	.string "acquaintance.$"
# 54 "data/maps/Route13_Frlg/scripts.pory"

# 55 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_GwenDefeat::
# 56 "data/maps/Route13_Frlg/scripts.pory"
	.string "Good going!\n"
# 57 "data/maps/Route13_Frlg/scripts.pory"
	.string "You totally won!$"
# 58 "data/maps/Route13_Frlg/scripts.pory"

# 59 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_GwenPostBattle::
# 60 "data/maps/Route13_Frlg/scripts.pory"
	.string "You have to make POKéMON battle\n"
# 61 "data/maps/Route13_Frlg/scripts.pory"
	.string "to toughen them up.$"
# 62 "data/maps/Route13_Frlg/scripts.pory"

# 63 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_AlmaIntro::
# 64 "data/maps/Route13_Frlg/scripts.pory"
	.string "I found CARBOS in a cave once\n"
# 65 "data/maps/Route13_Frlg/scripts.pory"
	.string "while I was spelunking.$"
# 66 "data/maps/Route13_Frlg/scripts.pory"

# 67 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_AlmaDefeat::
# 68 "data/maps/Route13_Frlg/scripts.pory"
	.string "Oh, too bad!\n"
# 69 "data/maps/Route13_Frlg/scripts.pory"
	.string "I just messed up!$"
# 70 "data/maps/Route13_Frlg/scripts.pory"

# 71 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_AlmaPostBattle::
# 72 "data/maps/Route13_Frlg/scripts.pory"
	.string "CARBOS boosted the SPEED of my\n"
# 73 "data/maps/Route13_Frlg/scripts.pory"
	.string "POKéMON.$"
# 74 "data/maps/Route13_Frlg/scripts.pory"

# 75 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_PerryIntro::
# 76 "data/maps/Route13_Frlg/scripts.pory"
	.string "I'm not going to lose.\n"
# 77 "data/maps/Route13_Frlg/scripts.pory"
	.string "Not when the wind's blowing my way!$"
# 78 "data/maps/Route13_Frlg/scripts.pory"

# 79 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_PerryDefeat::
# 80 "data/maps/Route13_Frlg/scripts.pory"
	.string "The wind turned!$"
# 81 "data/maps/Route13_Frlg/scripts.pory"

# 82 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_PerryPostBattle::
# 83 "data/maps/Route13_Frlg/scripts.pory"
	.string "I'm beat.\n"
# 84 "data/maps/Route13_Frlg/scripts.pory"
	.string "I guess I'll FLY home.$"
# 85 "data/maps/Route13_Frlg/scripts.pory"

# 86 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_LolaIntro::
# 87 "data/maps/Route13_Frlg/scripts.pory"
	.string "Sure, I'll play with you, sweetie.$"
# 88 "data/maps/Route13_Frlg/scripts.pory"

# 89 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_LolaDefeat::
# 90 "data/maps/Route13_Frlg/scripts.pory"
	.string "Oh!\n"
# 91 "data/maps/Route13_Frlg/scripts.pory"
	.string "You little beast!$"
# 92 "data/maps/Route13_Frlg/scripts.pory"

# 93 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_LolaPostBattle::
# 94 "data/maps/Route13_Frlg/scripts.pory"
	.string "I wonder which is stronger, male or\n"
# 95 "data/maps/Route13_Frlg/scripts.pory"
	.string "female POKéMON?$"
# 96 "data/maps/Route13_Frlg/scripts.pory"

# 97 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SheilaIntro::
# 98 "data/maps/Route13_Frlg/scripts.pory"
	.string "Do you want to battle some\n"
# 99 "data/maps/Route13_Frlg/scripts.pory"
	.string "POKéMON with me?$"
# 100 "data/maps/Route13_Frlg/scripts.pory"

# 101 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SheilaDefeat::
# 102 "data/maps/Route13_Frlg/scripts.pory"
	.string "It's over already?$"
# 103 "data/maps/Route13_Frlg/scripts.pory"

# 104 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SheilaPostBattle::
# 105 "data/maps/Route13_Frlg/scripts.pory"
	.string "I don't know anything about\n"
# 106 "data/maps/Route13_Frlg/scripts.pory"
	.string "POKéMON actually.\p"
# 107 "data/maps/Route13_Frlg/scripts.pory"
	.string "The ones I use… I picked them\n"
# 108 "data/maps/Route13_Frlg/scripts.pory"
	.string "for their looks!$"
# 109 "data/maps/Route13_Frlg/scripts.pory"

# 110 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_JaredIntro::
# 111 "data/maps/Route13_Frlg/scripts.pory"
	.string "What're you lookin' at?$"
# 112 "data/maps/Route13_Frlg/scripts.pory"

# 113 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_JaredDefeat::
# 114 "data/maps/Route13_Frlg/scripts.pory"
	.string "Dang!\n"
# 115 "data/maps/Route13_Frlg/scripts.pory"
	.string "Stripped gears!$"
# 116 "data/maps/Route13_Frlg/scripts.pory"

# 117 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_JaredPostBattle::
# 118 "data/maps/Route13_Frlg/scripts.pory"
	.string "Get lost!$"
# 119 "data/maps/Route13_Frlg/scripts.pory"

# 120 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_RobertIntro::
# 121 "data/maps/Route13_Frlg/scripts.pory"
	.string "I always go with bird POKéMON.\n"
# 122 "data/maps/Route13_Frlg/scripts.pory"
	.string "I've dedicated myself to them.$"
# 123 "data/maps/Route13_Frlg/scripts.pory"

# 124 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_RobertDefeat::
# 125 "data/maps/Route13_Frlg/scripts.pory"
	.string "Out of power!$"
# 126 "data/maps/Route13_Frlg/scripts.pory"

# 127 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_RobertPostBattle::
# 128 "data/maps/Route13_Frlg/scripts.pory"
	.string "I wish I could fly like PIDGEY and\n"
# 129 "data/maps/Route13_Frlg/scripts.pory"
	.string "PIDGEOTTO…$"
# 130 "data/maps/Route13_Frlg/scripts.pory"

# 131 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_LookToLeftOfThatPost::
# 132 "data/maps/Route13_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 133 "data/maps/Route13_Frlg/scripts.pory"
	.string "Look, look!\n"
# 134 "data/maps/Route13_Frlg/scripts.pory"
	.string "Look to the left of that post!$"
# 135 "data/maps/Route13_Frlg/scripts.pory"

# 136 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_SelectToSwitchItems::
# 137 "data/maps/Route13_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 138 "data/maps/Route13_Frlg/scripts.pory"
	.string "Use SELECT to switch items in the\n"
# 139 "data/maps/Route13_Frlg/scripts.pory"
	.string "ITEMS window.$"
# 140 "data/maps/Route13_Frlg/scripts.pory"

# 141 "data/maps/Route13_Frlg/scripts.pory"
Route13_Text_RouteSign::
# 142 "data/maps/Route13_Frlg/scripts.pory"
	.string "ROUTE 13\n"
# 143 "data/maps/Route13_Frlg/scripts.pory"
	.string "North to SILENCE BRIDGE$"
