# 1 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"

# 2 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
ThreeIsland_House2_Frlg_MapScripts::
# 3 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"

# 5 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
ThreeIsland_House2_EventScript_Man::
# 6 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	lock
# 7 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	faceplayer
# 8 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	famechecker FAMECHECKER_SABRINA, 1
# 9 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	msgbox ThreeIsland_House2_Text_IAdmireSabrina
# 10 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	release
# 11 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	end
# 12 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"

# 13 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
ThreeIsland_House2_EventScript_Rocker::
# 14 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	msgbox ThreeIsland_House2_Text_CantMakeThisSpoonBend, MSGBOX_NPC
# 15 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	end
# 16 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"

# 17 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
ThreeIsland_House2_Text_CantMakeThisSpoonBend::
# 18 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "Urrrrrrrrgggghhhh…\n"
# 19 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "Kwaaaaah!\p"
# 20 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "…It's useless! I can't make this\n"
# 21 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "spoon bend with my mind.\p"
# 22 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "Maybe I really don't have any\n"
# 23 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "psychic powers.$"
# 24 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"

# 25 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
ThreeIsland_House2_Text_IAdmireSabrina::
# 26 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "You know about a girl GYM LEADER\n"
# 27 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "in SAFFRON CITY?\p"
# 28 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "She uses PSYCHIC-type POKéMON,\n"
# 29 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "right?\p"
# 30 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "I admire her, I really do.\p"
# 31 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "I've heard that she's one cool\n"
# 32 "data/maps/ThreeIsland_House2_Frlg/scripts.pory"
	.string "customer and beautiful, too.$"
